
const I18N={
 zh:{title:"图片分类运输带",subtitle:"老师上传图片题目，学生把运输带上的图片分类到正确区域。",setup:"设置题库",fullscreen:"全屏",restart:"重开",setupTitle:"图片分类运输带｜老师设置",setupHelp:"老师可以设定分类名称，然后按分类顺序上传图片。学生看到运输带上的图片后，点击正确的分类区域。也可以切换成文字分类模式。",scoreTitle:"成绩",score:"分数",left:"剩余",correct:"正确",wrong:"错误",ruleTitle:"玩法说明",ruleText:"图片会一张一张出现在运输带上。学生需要判断图片属于哪一个类别，并点击下方正确分类区。答对加分，答错扣分。",round:"题目",hint:"请选择下方正确的分类区域。",listTitle:"题目清单",buildCats:"生成分类上传区",loadSample:"载入示范",start:"开始游戏",preview:"预览题目",category:"分类",upload:"上传图片",catName:"分类名称",again:"再玩一次",finish:"完成！",finalScore:"最终得分",noItems:"请先上传图片，或载入示范题目。",textPlaceholder:"文字分类格式：题目 | 正确分类\\n例如：苹果 | 水果",imageMode:"图片分类",textMode:"文字分类"},
 en:{title:"Image Classification Conveyor",subtitle:"Teachers upload images. Students classify each conveyor image into the correct category.",setup:"Question settings",fullscreen:"Fullscreen",restart:"Restart",setupTitle:"Image Classification Conveyor | Teacher Settings",setupHelp:"Set category names, then upload images under each category in order. Students see one image at a time on the conveyor and click the correct category. Text classification is also supported.",scoreTitle:"Score",score:"Score",left:"Left",correct:"Correct",wrong:"Wrong",ruleTitle:"How to play",ruleText:"Images appear on the conveyor one by one. Students choose the correct category zone. Correct answers add points; wrong answers deduct points.",round:"Item",hint:"Choose the correct category below.",listTitle:"Item list",buildCats:"Build upload boxes",loadSample:"Load sample",start:"Start game",preview:"Item preview",category:"Category",upload:"Upload images",catName:"Category name",again:"Play again",finish:"Finished!",finalScore:"Final score",noItems:"Please upload images or load sample items first.",textPlaceholder:"Text format: Item | Correct category\\nExample: Apple | Fruit",imageMode:"Image classification",textMode:"Text classification"},
 ms:{title:"Tali Sawat Klasifikasi Gambar",subtitle:"Guru memuat naik gambar. Murid mengelaskan gambar pada tali sawat ke kategori yang betul.",setup:"Tetapan soalan",fullscreen:"Skrin penuh",restart:"Mula semula",setupTitle:"Tali Sawat Klasifikasi Gambar | Tetapan Guru",setupHelp:"Tetapkan nama kategori, kemudian muat naik gambar mengikut kategori. Murid melihat satu gambar pada tali sawat dan klik kategori yang betul. Mod teks juga disokong.",scoreTitle:"Markah",score:"Markah",left:"Baki",correct:"Betul",wrong:"Salah",ruleTitle:"Cara bermain",ruleText:"Gambar muncul satu demi satu pada tali sawat. Murid klik zon kategori yang betul. Jawapan betul tambah markah; jawapan salah tolak markah.",round:"Item",hint:"Pilih kategori yang betul di bawah.",listTitle:"Senarai item",buildCats:"Bina ruang muat naik",loadSample:"Muat contoh",start:"Mula permainan",preview:"Pratonton item",category:"Kategori",upload:"Muat naik gambar",catName:"Nama kategori",again:"Main lagi",finish:"Selesai!",finalScore:"Markah akhir",noItems:"Sila muat naik gambar atau muat item contoh dahulu.",textPlaceholder:"Format teks: Item | Kategori betul\\nContoh: Epal | Buah",imageMode:"Klasifikasi gambar",textMode:"Klasifikasi teks"}
};
let lang=new URLSearchParams(location.search).get("lang")||localStorage.getItem("classify_lang")||"zh";
let items=[],queue=[],current=null,cats=[],score=0,correct=0,wrong=0,index=0,timerId=null,endAt=0,started=false;
const $=s=>document.querySelector(s);function T(k){return(I18N[lang]||I18N.zh)[k]||k}
function applyLang(){document.documentElement.lang=lang==="zh"?"zh-Hans":lang;document.title=T("title");["title","subtitle","setupTitle","setupHelp","scoreTitle","ruleTitle","ruleText","listTitle"].forEach(id=>$("#"+id).textContent=T(id));$("#previewTitle").textContent=T("preview");$("#setupBtn").textContent=T("setup");$("#fullBtn").textContent=T("fullscreen");$("#resetBtn").textContent=T("restart");$("#buildCatsBtn").textContent=T("buildCats");$("#loadSampleBtn").textContent=T("loadSample");$("#startBtn").textContent=T("start");$("#againBtn").textContent=T("again");$("#scoreLabel").textContent=T("score");$("#leftLabel").textContent=T("left");$("#correctLabel").textContent=T("correct");$("#wrongLabel").textContent=T("wrong");$("#hintText").textContent=T("hint");$("#textItems").placeholder=T("textPlaceholder");$("#lang").value=lang;$("#setupLang").value=lang;renderCats();updateScore();}
function renderCats(){const n=Number($("#catCount").value||3),grid=$("#catGrid");const old=[...grid.querySelectorAll(".cat-name")].map(x=>x.value);grid.innerHTML="";for(let i=0;i<n;i++){const name=old[i]||defaultCat(i);const box=document.createElement("div");box.className="cat-box";box.innerHTML=`<label>${T("catName")} ${i+1}</label><input class="input cat-name" value="${name}"><label style="margin-top:8px">${T("upload")}</label><input class="input cat-file" type="file" accept="image/*" multiple>`;grid.appendChild(box)}[...grid.querySelectorAll(".cat-file")].forEach(input=>input.onchange=()=>{buildItems(false);renderPreview();});}
function defaultCat(i){const zh=["水果","动物","交通","人物","其他"],en=["Fruit","Animal","Transport","People","Others"],ms=["Buah","Haiwan","Pengangkutan","Manusia","Lain-lain"];return (lang==="en"?en:lang==="ms"?ms:zh)[i]||`${T("category")} ${i+1}`}
function buildItems(showAlert=true){const mode=$("#mode").value;cats=[...document.querySelectorAll(".cat-name")].map(x=>x.value.trim()).filter(Boolean);let out=[];if(mode==="image"){[...document.querySelectorAll(".cat-box")].forEach((box,i)=>{const cat=box.querySelector(".cat-name").value.trim()||defaultCat(i);[...box.querySelector(".cat-file").files].forEach(f=>out.push({type:"image",name:f.name,cat,url:URL.createObjectURL(f)}));});}else{const rows=$("#textItems").value.split("\\n").map(x=>x.trim()).filter(Boolean);rows.forEach(row=>{const p=row.split("|").map(x=>x.trim());if(p.length>=2)out.push({type:"text",name:p[0],cat:p[1],url:""});});cats=[...new Set(out.map(x=>x.cat))];}items=out;if(showAlert&&!items.length)alert(T("noItems"));return items;}
function renderPreview(){const list=$("#previewList");list.innerHTML="";items.forEach(it=>{const div=document.createElement("div");div.className="preview";div.innerHTML=`<div class="preview-img" style="${it.type==="image"?`background-image:url('${it.url}')`:""}">${it.type==="text"?it.name:""}</div><b>${it.cat}</b><br><span>${it.name}</span>`;list.appendChild(div);});}
function loadSample(){cats=lang==="en"?["Fruit","Animal","Transport"]:lang==="ms"?["Buah","Haiwan","Pengangkutan"]:["水果","动物","交通"];$("#catCount").value="3";renderCats();$("#mode").value="text";$("#textItems").value=lang==="en"?"Apple | Fruit\\nCat | Animal\\nBus | Transport\\nBanana | Fruit\\nDog | Animal":lang==="ms"?"Epal | Buah\\nKucing | Haiwan\\nBas | Pengangkutan\\nPisang | Buah\\nAnjing | Haiwan":"苹果 | 水果\\n小猫 | 动物\\n巴士 | 交通\\n香蕉 | 水果\\n小狗 | 动物";buildItems(false);renderPreview();}
function start(){buildItems(true);if(!items.length)return;queue=$("#shuffleMode").value==="yes"?[...items].sort(()=>Math.random()-.5):[...items];score=0;correct=0;wrong=0;index=0;started=true;endAt=Date.now()+Number($("#timeLimit").value||180)*1000;$("#setup").classList.add("hidden");renderDropzones();renderMiniList();nextItem();timerId=setInterval(tick,200);updateScore();}
function tick(){const left=Math.max(0,endAt-Date.now());const s=Math.ceil(left/1000);$("#timer").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(left<=0)finish();}
function renderDropzones(){$("#dropzones").innerHTML=cats.map(c=>`<button class="dropzone" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll(".dropzone").forEach(btn=>btn.onclick=()=>answer(btn.dataset.cat,btn));}
function renderMiniList(){$("#miniList").innerHTML=queue.map(it=>`<div class="mini"><div class="thumb" style="${it.type==="image"?`background-image:url('${it.url}')`:"display:grid;place-items:center"}">${it.type==="text"?"T":""}</div><div><b>${it.name}</b><br><span>${it.cat}</span></div></div>`).join("")}
function nextItem(){if(index>=queue.length){finish();return;}current=queue[index];$("#roundText").textContent=`${T("round")} ${index+1}/${queue.length}`;$("#itemCard").classList.remove("hidden");$("#itemLabel").textContent=current.name;const img=$("#itemImg");img.style.backgroundImage=current.type==="image"?`url('${current.url}')`:"";img.textContent=current.type==="text"?current.name:"";}
function answer(cat,btn){if(!current)return;const ok=cat===current.cat;btn.classList.add(ok?"good":"bad");setTimeout(()=>btn.classList.remove("good","bad"),450);if(ok){score+=10;correct++;}else{score=Math.max(0,score-5);wrong++;}index++;updateScore();nextItem();}
function updateScore(){$("#score").textContent=score;$("#correctCount").textContent=correct;$("#wrongCount").textContent=wrong;$("#leftCount").textContent=queue.length?Math.max(0,queue.length-index):items.length;}
function finish(){clearInterval(timerId);current=null;$("#itemCard").classList.add("hidden");$("#winTitle").textContent=T("finish");$("#winDesc").textContent=`${T("finalScore")}：${score}｜${T("correct")}：${correct}｜${T("wrong")}：${wrong}`;$("#win").classList.remove("hidden");}
$("#lang").onchange=e=>{lang=e.target.value;localStorage.setItem("classify_lang",lang);applyLang()};$("#setupLang").onchange=e=>{lang=e.target.value;localStorage.setItem("classify_lang",lang);applyLang()};$("#catCount").onchange=renderCats;$("#mode").onchange=()=>{renderCats();};$("#buildCatsBtn").onclick=renderCats;$("#loadSampleBtn").onclick=loadSample;$("#startBtn").onclick=start;$("#setupBtn").onclick=()=>$("#setup").classList.remove("hidden");$("#resetBtn").onclick=()=>location.reload();$("#fullBtn").onclick=()=>document.documentElement.requestFullscreen?.();applyLang();
