
const $=s=>document.querySelector(s);let lang='zh',qs=[],turn='A',bossMax=300,boss=300,hpMax=100,hpA=100,hpB=100,scoreA=0,scoreB=0,logs=[],pendingDmg=0,endAt=0,timerId=null;
const L={zh:{title:'地牢巨龍討伐戰',sub:'兩隊合作又競爭，答題攻擊巨龍，守住隊伍生命值。',setup:'設定題庫',full:'全屏',reset:'重開',teamTitle:'隊伍狀態',ruleTitle:'玩法',rule:'輪到隊伍選擇攻擊方式並答題。答對會攻擊巨龍，答錯巨龍會反擊。擊倒巨龍即勝利；若兩隊生命都歸零則失敗。',A:'勇者隊',B:'法師隊',boss:'巨龍生命',turn:t=>(t==='A'?'勇者隊':'法師隊')+'行動',hint:'選擇一種攻擊，回答問題。',atk1:'普通攻擊',atk2:'火焰攻擊',atk3:'必殺攻擊',pass:'換隊',log:'戰鬥記錄',setupTitle:'地牢巨龍討伐戰｜老師設定',setupHelp:'題庫格式：題目|選項A|選項B|選項C|選項D|正確答案編號。每行一題。',sample:'載入示範',start:'開始遊戲',correct:'答對！造成傷害',wrong:'答錯！巨龍反擊',win:'巨龍被擊敗！',lose:'隊伍全滅，挑戰失敗。',again:'再玩一次'},
en:{title:'Dungeon Dragon Raid',sub:'Two teams answer questions to attack the dragon and protect their HP.',setup:'Questions',full:'Fullscreen',reset:'Restart',teamTitle:'Team status',ruleTitle:'How to play',rule:'A team chooses an attack and answers a question. Correct answers damage the dragon; wrong answers trigger a counterattack. Defeat the dragon to win.',A:'Warriors',B:'Mages',boss:'Dragon HP',turn:t=>(t==='A'?'Warriors':'Mages')+' turn',hint:'Choose an attack and answer.',atk1:'Normal',atk2:'Flame',atk3:'Ultimate',pass:'Switch',log:'Battle log',setupTitle:'Dungeon Dragon Raid | Settings',setupHelp:'Format: question|A|B|C|D|correct number. One question per line.',sample:'Load sample',start:'Start',correct:'Correct! Damage dealt',wrong:'Wrong! Dragon counterattacks',win:'Dragon defeated!',lose:'All teams fell. Challenge failed.',again:'Play again'},
ms:{title:'Serbuan Naga Bawah Tanah',sub:'Dua kumpulan menjawab soalan untuk menyerang naga dan melindungi HP.',setup:'Soalan',full:'Skrin penuh',reset:'Mula semula',teamTitle:'Status kumpulan',ruleTitle:'Cara bermain',rule:'Pilih serangan dan jawab soalan. Jawapan betul mencederakan naga; jawapan salah membuat naga menyerang balik.',A:'Pahlawan',B:'Ahli Sihir',boss:'HP Naga',turn:t=>(t==='A'?'Pahlawan':'Ahli Sihir')+' bergerak',hint:'Pilih serangan dan jawab.',atk1:'Serangan biasa',atk2:'Api',atk3:'Muktamad',pass:'Tukar',log:'Rekod',setupTitle:'Serbuan Naga | Tetapan',setupHelp:'Format: soalan|A|B|C|D|nombor jawapan betul. Satu soalan setiap baris.',sample:'Muat contoh',start:'Mula',correct:'Betul! Kerosakan diberi',wrong:'Salah! Naga membalas',win:'Naga ditewaskan!',lose:'Semua kumpulan tewas.',again:'Main lagi'}};const t=k=>L[lang][k]||k;
function sample(){$('#questionText').value='哪一個密碼較安全？|123456|生日|BlueSky!2026|名字|3\nAI 主要從什麼學習？|魔法|訓練資料|運氣|空氣|2\n看到可疑連結應該？|馬上點|分享朋友|先檢查來源|輸入密碼|3\n哪一個是圖片檔？|photo.jpg|song.mp3|video.mp4|essay.docx|1';}
function parse(){return $('#questionText').value.split('\n').map(r=>r.trim()).filter(Boolean).map(r=>{let p=r.split('|').map(x=>x.trim());return{q:p[0],opts:p.slice(1,5),ans:Number(p[5]||1)-1}}).filter(x=>x.q&&x.opts.length>=4)}
function apply(){document.title=t('title');$('#title').textContent=t('title');$('#subtitle').textContent=t('sub');$('#setupBtn').textContent=t('setup');$('#fullBtn').textContent=t('full');$('#resetBtn').textContent=t('reset');$('#teamTitle').textContent=t('teamTitle');$('#ruleTitle').textContent=t('ruleTitle');$('#ruleText').textContent=t('rule');$('#teamA').textContent=$('#teamA2').textContent=t('A');$('#teamB').textContent=$('#teamB2').textContent=t('B');$('#bossLabel').textContent=t('boss');$('#hintText').textContent=t('hint');$('#atk1').textContent=t('atk1');$('#atk2').textContent=t('atk2');$('#atk3').textContent=t('atk3');$('#passBtn').textContent=t('pass');$('#logTitle').textContent=t('log');$('#setupTitle').textContent=t('setupTitle');$('#setupHelp').textContent=t('setupHelp');$('#sampleBtn').textContent=t('sample');$('#startBtn').textContent=t('start');$('#againBtn').textContent=t('again');render()}
function start(){qs=parse();if(!qs.length){sample();qs=parse()}bossMax=Number($('#bossMaxInput').value||300);boss=bossMax;hpMax=Number($('#teamHpInput').value||100);hpA=hpB=hpMax;scoreA=scoreB=0;logs=[];turn='A';$('#setup').classList.add('hidden');endAt=Date.now()+Number($('#timeLimit').value||360)*1000;clearInterval(timerId);timerId=setInterval(tick,200);render()}
function tick(){let s=Math.max(0,Math.ceil((endAt-Date.now())/1000));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(s<=0)finish(false)}
function render(){$('#turnText').textContent=t('turn')(turn);$('#bossHp').textContent=boss;$('#hpA').style.width=(hpA/hpMax*100)+'%';$('#hpB').style.width=(hpB/hpMax*100)+'%';$('#hpAText').textContent='HP '+hpA+'/'+hpMax;$('#hpBText').textContent='HP '+hpB+'/'+hpMax;$('#scoreA').textContent=scoreA;$('#scoreB').textContent=scoreB;$('#cardA').classList.toggle('active',turn==='A');$('#cardB').classList.toggle('active',turn==='B');$('#logs').innerHTML=logs.map(x=>'<div class="log">'+x+'</div>').join('')}
function ask(dmg){pendingDmg=dmg;let q=qs[Math.floor(Math.random()*qs.length)];$('#modalTitle').textContent=t('turn')(turn);$('#modalMeta').textContent='Damage '+dmg;$('#modalQ').textContent=q.q;$('#qOptions').innerHTML='';q.opts.forEach((o,i)=>{let b=document.createElement('button');b.className='opt';b.textContent=String.fromCharCode(65+i)+'. '+o;b.onclick=()=>answer(i===q.ans,dmg);$('#qOptions').appendChild(b)});$('#quizModal').classList.remove('hidden')}
function answer(ok,dmg){$('#quizModal').classList.add('hidden');if(ok){boss=Math.max(0,boss-dmg);if(turn==='A')scoreA+=dmg;else scoreB+=dmg;logs.unshift('✅ '+t('correct')+' '+dmg)}else{if(turn==='A')hpA=Math.max(0,hpA-20);else hpB=Math.max(0,hpB-20);logs.unshift('❌ '+t('wrong')+' -20 HP')}logs=logs.slice(0,8);if(boss<=0)finish(true);else if(hpA<=0&&hpB<=0)finish(false);else{turn=turn==='A'?'B':'A';render()}}
function finish(win){clearInterval(timerId);$('#win').classList.remove('hidden');$('#winTitle').textContent=win?t('win'):t('lose');$('#winDesc').textContent=t('A')+' '+scoreA+' ｜ '+t('B')+' '+scoreB}
document.querySelectorAll('.skill').forEach(b=>b.onclick=()=>ask(Number(b.dataset.dmg)));$('#lang').onchange=e=>{lang=e.target.value;apply()};$('#setupBtn').onclick=()=>$('#setup').classList.remove('hidden');$('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('#resetBtn').onclick=()=>location.reload();$('#passBtn').onclick=()=>{turn=turn==='A'?'B':'A';render()};$('#sampleBtn').onclick=sample;$('#startBtn').onclick=start;sample();apply();
