
let lang="zh";
let setupQuestions=[],questionSets=[],currentIndex=0,selectedLabel=null,assignments={},totalAttempts=0,score=0,correctRounds=0,timerId=null,endAt=0,logs=[],roundDone=false;
const $=s=>document.querySelector(s);
function T(k){return ({
 zh:{title:"图片标签配对赛",subtitle:"老师可建立 5 题或 10 题，上传图片并设置 3–5 个标注位置。个人作答稳定版。",setup:"设置题库",fullscreen:"全屏",restart:"重开",setupTitle:"图片标签配对赛｜个人作答设置",setupHelp:"每一题上传一张图片，输入 3–5 个标签。先点选标签按钮，再点击图片位置设定标注点。若老师只是快速建立题组，系统会先放入示范占位图，之后可再替换成真实图片。",scoreTitle:"成绩",score:"分数",round:"题组",attempt:"检查次数",correct:"完成题数",ruleTitle:"玩法说明",ruleText:"老师先在图片上设置标注位置。学生作答时，先点击标签，再点击图片上的标注点，并逐题完成所有题组。",hint:"先选择标签，再点击对应标注点。",check:"检查答案",next:"下一题",clear:"清空本题",logTitle:"记录",qListTitle:"题组清单",sample5:"载入 5 题示范",buildPreset:"建立题组",addQuestion:"新增一题",start:"开始游戏",again:"再玩一次",finish:"完成！",finalScore:"最终得分",wrong:"还有标签位置不正确。",correctAll:"本题正确！",qTitle:"题目标题",labels:"标签：每行一个，3–5 个",upload:"上传图片",setPos:"点标签，再点图片设定位置",remove:"删除",empty:"请至少保留 1 题；每题需要 3–5 个标签，并完成所有标注位置。",pickLabel:"请选择一个标签"},
 en:{title:"Image Label Matching",subtitle:"Create 5 or 10 sets. Upload images and set 3–5 label positions. Stable individual mode.",setup:"Question settings",fullscreen:"Fullscreen",restart:"Restart",setupTitle:"Image Label Matching | Individual Settings",setupHelp:"For each set, upload one image and enter 3–5 labels. Select a label button, then click the image to set its position. Quick-created sets include placeholder images that can be replaced later.",scoreTitle:"Score",score:"Score",round:"Sets",attempt:"Checks",correct:"Completed",ruleTitle:"How to play",ruleText:"Teachers set label positions on images first. Students select a label, then click the correct marker and complete all sets one by one.",hint:"Select a label, then click the matching marker.",check:"Check answer",next:"Next set",clear:"Clear this set",logTitle:"Log",qListTitle:"Set list",sample5:"Load 5 samples",buildPreset:"Build sets",addQuestion:"Add set",start:"Start game",again:"Play again",finish:"Finished!",finalScore:"Final score",wrong:"Some labels are in the wrong positions.",correctAll:"This set is correct!",qTitle:"Question title",labels:"Labels: one per line, 3–5 labels",upload:"Upload image",setPos:"Select label, then click image to set position",remove:"Remove",empty:"Please keep at least 1 set. Each set needs 3–5 labels and all label positions.",pickLabel:"Please select a label"},
 ms:{title:"Padanan Label Gambar",subtitle:"Bina 5 atau 10 set. Muat naik gambar dan tetapkan 3–5 posisi label. Mod individu stabil.",setup:"Tetapan soalan",fullscreen:"Skrin penuh",restart:"Mula semula",setupTitle:"Padanan Label Gambar | Tetapan Individu",setupHelp:"Untuk setiap set, muat naik satu gambar dan masukkan 3–5 label. Pilih butang label, kemudian klik pada gambar untuk menetapkan posisi. Set pantas mengandungi gambar contoh yang boleh diganti kemudian.",scoreTitle:"Markah",score:"Markah",round:"Set",attempt:"Semakan",correct:"Selesai",ruleTitle:"Cara bermain",ruleText:"Guru menetapkan posisi label pada gambar dahulu. Murid memilih label, kemudian klik penanda yang betul dan menyelesaikan semua set.",hint:"Pilih label, kemudian klik penanda yang sepadan.",check:"Semak jawapan",next:"Seterusnya",clear:"Kosongkan set",logTitle:"Rekod",qListTitle:"Senarai set",sample5:"Muat 5 contoh",buildPreset:"Bina set",addQuestion:"Tambah set",start:"Mula permainan",again:"Main lagi",finish:"Selesai!",finalScore:"Markah akhir",wrong:"Masih ada label di posisi salah.",correctAll:"Set ini betul!",qTitle:"Tajuk soalan",labels:"Label: satu setiap baris, 3–5 label",upload:"Muat naik gambar",setPos:"Pilih label, kemudian klik gambar untuk tetapkan posisi",remove:"Buang",empty:"Sila kekalkan sekurang-kurangnya 1 set. Setiap set memerlukan 3–5 label dan semua posisi label.",pickLabel:"Sila pilih label"}
}[lang]||{})[k]||k}
function svgData(title,labels,bg="#0f766e"){
 const safe=encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="560"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="${bg}"/><stop offset="1" stop-color="#020617"/></linearGradient></defs><rect width="900" height="560" rx="30" fill="url(#g)"/><circle cx="180" cy="170" r="80" fill="rgba(255,255,255,.18)"/><rect x="360" y="120" width="280" height="160" rx="28" fill="rgba(255,255,255,.13)"/><path d="M160 390 C310 280 510 470 730 330" stroke="rgba(255,255,255,.35)" stroke-width="18" fill="none" stroke-linecap="round"/><text x="450" y="70" text-anchor="middle" fill="#fff" font-family="Arial" font-size="40" font-weight="900">${title}</text><text x="450" y="520" text-anchor="middle" fill="#d1fae5" font-family="Arial" font-size="24">${labels.join(" · ")}</text></svg>`);
 return `data:image/svg+xml,${safe}`;
}
function defaultPositions(n){const p={3:[{x:.28,y:.32},{x:.50,y:.50},{x:.72,y:.68}],4:[{x:.25,y:.28},{x:.72,y:.28},{x:.28,y:.70},{x:.72,y:.70}],5:[{x:.20,y:.28},{x:.50,y:.24},{x:.80,y:.28},{x:.35,y:.72},{x:.65,y:.72}]};return (p[n]||p[3]).map(a=>({...a}))}
function blankQuestion(i){const labels=["标签1","标签2","标签3"];const title=`Q${i+1}`;return{title,imageUrl:svgData(title,labels,"#0f766e"),imageName:"placeholder.svg",labels,positions:defaultPositions(3),activeIndex:0}}
function sampleSets(){return[{title:"植物部位",labels:["根","茎","叶","花"],pos:[[.28,.72],[.45,.58],[.58,.40],[.72,.25]],bg:"#166534"},{title:"电脑设备",labels:["屏幕","键盘","鼠标"],pos:[[.48,.28],[.48,.68],[.72,.70]],bg:"#1d4ed8"},{title:"课室物品",labels:["白板","桌子","椅子"],pos:[[.50,.23],[.42,.63],[.68,.65]],bg:"#7c2d12"},{title:"地图标注",labels:["北方","河流","城市"],pos:[[.50,.18],[.35,.58],[.68,.50]],bg:"#0f766e"},{title:"AI 项目元素",labels:["资料","模型","结果"],pos:[[.30,.48],[.50,.42],[.70,.48]],bg:"#581c87"}]}
function loadSamples(n=5){const base=sampleSets();setupQuestions=[];for(let i=0;i<n;i++){const s=base[i%base.length];setupQuestions.push({title:n>base.length?`${s.title} ${Math.floor(i/base.length)+1}`:s.title,imageUrl:svgData(s.title,s.labels,s.bg),imageName:"sample.svg",labels:[...s.labels],positions:s.pos.map(p=>({x:p[0],y:p[1]})),activeIndex:0});}renderSetupEditors();}
function buildPreset(n){setupQuestions=[];for(let i=0;i<n;i++)setupQuestions.push(blankQuestion(i));renderSetupEditors();}
function addQuestion(){setupQuestions.push(blankQuestion(setupQuestions.length));renderSetupEditors();}
function removeQuestion(i){setupQuestions.splice(i,1);renderSetupEditors();}
function applyLang(){document.documentElement.lang=lang==="zh"?"zh-Hans":lang;document.title=T("title");["title","subtitle","setupTitle","setupHelp","scoreTitle","ruleTitle","ruleText","qListTitle","logTitle"].forEach(id=>{const el=$("#"+id);if(el)el.textContent=T(id)});$("#setupBtn").textContent=T("setup");$("#fullBtn").textContent=T("fullscreen");$("#resetBtn").textContent=T("restart");$("#hintText").textContent=T("hint");$("#checkBtn").textContent=T("check");$("#nextBtn").textContent=T("next");$("#clearBtn").textContent=T("clear");$("#sample5Btn").textContent=T("sample5");$("#buildPresetBtn").textContent=T("buildPreset");$("#addQuestionBtn").textContent=T("addQuestion");$("#startBtn").textContent=T("start");$("#againBtn").textContent=T("again");$("#scoreLabel").textContent=T("score");$("#roundLabel").textContent=T("round");$("#attemptLabel").textContent=T("attempt");$("#correctLabel").textContent=T("correct");$("#lang").value=lang;$("#setupLang").value=lang;renderSetupEditors();updateStats();}
function renderSetupEditors(){const box=$("#questionEditors");if(!box)return;box.innerHTML="";setupQuestions.forEach((q,i)=>{const div=document.createElement("div");div.className="q-editor";div.innerHTML=`<div class="q-editor-head"><b>Q${i+1}</b><button class="btn small remove-q">${T("remove")}</button></div><div class="q-editor-body"><div><input class="input q-title-input" placeholder="${T("qTitle")}" value="${q.title.replaceAll('"','&quot;')}"><label class="help">${T("upload")}</label><input class="input q-file-input" type="file" accept="image/*"><textarea class="input q-labels-input" placeholder="${T("labels")}">${q.labels.join("\n")}</textarea><div class="help">${T("setPos")}</div><div class="label-buttons"></div></div><div class="position-editor"></div></div>`;box.appendChild(div);const titleInput=div.querySelector(".q-title-input"),fileInput=div.querySelector(".q-file-input"),labelsInput=div.querySelector(".q-labels-input"),pos=div.querySelector(".position-editor"),buttons=div.querySelector(".label-buttons");titleInput.oninput=()=>{q.title=titleInput.value.trim()||`Q${i+1}`;};fileInput.onchange=e=>{const f=e.target.files[0];if(!f)return;q.imageUrl=URL.createObjectURL(f);q.imageName=f.name;renderSetupEditors();};labelsInput.onchange=()=>{let labels=labelsInput.value.split("\n").map(x=>x.trim()).filter(Boolean).slice(0,5);if(labels.length<3)labels=["标签1","标签2","标签3"];q.labels=labels;q.positions=labels.map((_,idx)=>q.positions[idx]||defaultPositions(labels.length)[idx]||{x:.5,y:.5});q.activeIndex=0;if(!q.imageUrl)q.imageUrl=svgData(q.title||"Q",labels);renderSetupEditors();};div.querySelector(".remove-q").onclick=()=>removeQuestion(i);pos.innerHTML=`<div class="stage-fallback">${q.title}</div><img class="setup-img" src="${q.imageUrl}" alt="">`;buttons.innerHTML=q.labels.map((lab,idx)=>`<button class="label-button ${q.activeIndex===idx?'active':''}" data-idx="${idx}">${idx+1}. ${lab}</button>`).join("");buttons.querySelectorAll(".label-button").forEach(btn=>btn.onclick=()=>{q.activeIndex=Number(btn.dataset.idx);renderSetupEditors();});pos.onclick=e=>{const r=pos.getBoundingClientRect();q.positions[q.activeIndex]={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};renderSetupEditors();};q.positions.forEach((p,idx)=>{if(!p)return;const m=document.createElement("div");m.className="pos-marker";m.style.left=(p.x*100)+"%";m.style.top=(p.y*100)+"%";m.textContent=idx+1;pos.appendChild(m);});});}
function parseSets(){return setupQuestions.filter(q=>q.labels.length>=3&&q.labels.length<=5).map(q=>{const labels=[...q.labels].slice(0,5);const positions=labels.map((_,i)=>q.positions[i]||defaultPositions(labels.length)[i]||{x:.5,y:.5});const imageUrl=q.imageUrl||svgData(q.title||"Q",labels);return{title:q.title||"Q",imageUrl,labels,positions:positions.map((p,i)=>({x:p.x,y:p.y,label:labels[i],index:i}))};});}
function start(){questionSets=parseSets();if(!questionSets.length){alert(T("empty"));return;}currentIndex=0;score=0;correctRounds=0;totalAttempts=0;logs=[];$("#setup").classList.add("hidden");loadRound(0);endAt=Date.now()+Number($("#timeLimit").value||600)*1000;clearInterval(timerId);timerId=setInterval(tick,200);updateStats();}
function tick(){const left=Math.max(0,endAt-Date.now());const s=Math.ceil(left/1000);$("#timer").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(left<=0)finish();}
function loadRound(i){roundDone=false;selectedLabel=null;assignments={};$("#nextBtn").classList.add("hidden");$("#checkBtn").classList.remove("hidden");renderRound();updateStats();}
function renderRound(){const q=questionSets[currentIndex];$("#questionTitle").textContent=q.title;const stage=$("#imageStage");stage.innerHTML=`<div class="stage-fallback">${q.title}</div><img class="stage-img" src="${q.imageUrl}" alt="">`+q.positions.map((p,i)=>`<div class="marker ${assignments[i]!==undefined?'assigned':'empty'}" data-marker="${i}" style="left:${p.x*100}%;top:${p.y*100}%">${assignments[i]!==undefined?q.labels[assignments[i]]:(i+1)}</div>`).join("");$("#labels").innerHTML=q.labels.map((lab,i)=>`<div class="label-chip ${selectedLabel===i?'selected':''} ${Object.values(assignments).includes(i)?'used':''}" data-label="${i}">${lab}</div>`).join("");document.querySelectorAll(".label-chip").forEach(ch=>ch.onclick=()=>{selectedLabel=Number(ch.dataset.label);renderRound();});document.querySelectorAll(".marker").forEach(m=>m.onclick=()=>assignMarker(Number(m.dataset.marker)));$("#roundText").textContent=`${T("round")}：${currentIndex+1}/${questionSets.length}`;renderLogs();renderQuestionList();}
function assignMarker(markerIdx){if(selectedLabel===null){alert(T("pickLabel"));return;}for(const k of Object.keys(assignments)){if(assignments[k]===selectedLabel)delete assignments[k];}assignments[markerIdx]=selectedLabel;renderRound();}
function clearSingle(){assignments={};selectedLabel=null;renderRound();}
function check(){if(roundDone)return;totalAttempts++;let ok=true;document.querySelectorAll(".marker").forEach((m,i)=>{const correct=assignments[i]===i;m.classList.toggle("good",correct);m.classList.toggle("bad",!correct);if(!correct)ok=false;});if(ok){roundDone=true;correctRounds++;score+=100;addLog(`✅ ${questionSets[currentIndex].title}｜${T("correctAll")} +100`);$("#checkBtn").classList.add("hidden");$("#nextBtn").classList.remove("hidden");if(currentIndex===questionSets.length-1)setTimeout(finish,700);}else addLog(`❌ ${questionSets[currentIndex].title}｜${T("wrong")}`);updateStats();renderQuestionList();}
function nextRound(){if(currentIndex<questionSets.length-1){currentIndex++;loadRound(currentIndex)}else finish();}
function updateStats(){$("#score").textContent=score;$("#attempts").textContent=totalAttempts;$("#correctRounds").textContent=correctRounds;$("#roundScore").textContent=`${currentIndex+1}/${questionSets.length||0}`}
function addLog(x){logs.unshift(x);logs=logs.slice(0,8);renderLogs()}
function renderLogs(){$("#logs").innerHTML=logs.map(x=>`<div class="log">${x}</div>`).join("")}
function renderQuestionList(){$("#questionList").innerHTML=questionSets.map((q,i)=>`<div class="q-pill ${i===currentIndex?'active':''} ${i<currentIndex||(i===currentIndex&&roundDone)?'done':''}">Q${i+1}｜${q.title}<br><span>${q.labels.length} labels</span></div>`).join("")}
function finish(){clearInterval(timerId);$("#winTitle").textContent=T("finish");$("#winDesc").textContent=`${T("finalScore")}：${score}｜${T("correct")}：${correctRounds}/${questionSets.length}｜${T("attempt")}：${totalAttempts}`;$("#win").classList.remove("hidden")}
$("#lang").onchange=e=>{lang=e.target.value;localStorage.setItem("labelpos_lang",lang);applyLang();};
$("#setupLang").onchange=e=>{lang=e.target.value;localStorage.setItem("labelpos_lang",lang);applyLang();};
$("#sample5Btn").onclick=()=>loadSamples(5);
$("#buildPresetBtn").onclick=()=>buildPreset(Number($("#questionPreset").value||5));
$("#addQuestionBtn").onclick=addQuestion;
$("#startBtn").onclick=start;
$("#checkBtn").onclick=check;
$("#nextBtn").onclick=nextRound;
$("#clearBtn").onclick=clearSingle;
$("#setupBtn").onclick=()=>$("#setup").classList.remove("hidden");
$("#resetBtn").onclick=()=>location.reload();
$("#fullBtn").onclick=()=>document.documentElement.requestFullscreen?.();
applyLang();loadSamples(5);
