
const $=s=>document.querySelector(s);let lang='zh',qs=[],tiles=[],pending=null,keys=0,relics=0,lives=5,score=0,target=3,logs=[],endAt=0,timerId=null;
const L={zh:{title:'海島遺跡尋寶戰',sub:'探索海島格子，答題解鎖遺跡、鑰匙與寶藏。',setup:'設定題庫',full:'全屏',reset:'重開',status:'探險狀態',ruleTitle:'玩法',rule:'點選島上的未知地點並回答題目。答對可獲得鑰匙、遺物或分數；答錯會觸發陷阱。收集 3 件遺物即可勝利。',round:'開始探索',hint:'選擇一個未探索格子。',goal:n=>`目標：${n} 件遺物`,explored:n=>`已探索：${n}/20`,trap:n=>`陷阱：${n}`,chest:n=>`寶箱：${n}`,mapHint:'有些格子是寶箱，有些是陷阱；答題正確才會揭開結果。',shuffle:'重新洗島',log:'探險記錄',setupTitle:'海島遺跡尋寶戰｜老師設定',setupHelp:'題庫格式：題目|選項A|選項B|選項C|選項D|正確答案編號。每行一題。',sample:'載入示範',start:'開始遊戲',correct:'答對，成功探索',wrong:'答錯，觸發陷阱',win:'找到足夠遺物，探險成功！',lose:'生命耗盡，探險失敗。',again:'再玩一次'},en:{title:'Island Relic Expedition',sub:'Explore island tiles. Answer questions to unlock relics, keys and treasure.',setup:'Questions',full:'Fullscreen',reset:'Restart',status:'Expedition status',ruleTitle:'How to play',rule:'Choose unexplored island locations and answer questions. Correct answers reveal keys, relics or points. Wrong answers trigger traps. Collect relics to win.',round:'Start exploring',hint:'Choose an unexplored tile.',goal:n=>`Goal: ${n} relics`,explored:n=>`Explored: ${n}/20`,trap:n=>`Traps: ${n}`,chest:n=>`Chests: ${n}`,mapHint:'Some tiles are chests, some are traps. Answer correctly to reveal them.',shuffle:'Shuffle island',log:'Expedition log',setupTitle:'Island Relic Expedition | Settings',setupHelp:'Format: question|A|B|C|D|correct number. One question per line.',sample:'Load sample',start:'Start',correct:'Correct! Exploration success',wrong:'Wrong! Trap triggered',win:'Enough relics found. Expedition success!',lose:'No lives left. Expedition failed.',again:'Play again'},ms:{title:'Ekspedisi Relik Pulau',sub:'Teroka petak pulau. Jawab soalan untuk membuka relik, kunci dan harta.',setup:'Soalan',full:'Skrin penuh',reset:'Mula semula',status:'Status ekspedisi',ruleTitle:'Cara bermain',rule:'Pilih lokasi belum diteroka dan jawab soalan. Betul membuka kunci, relik atau mata. Salah mencetuskan perangkap. Kumpul relik untuk menang.',round:'Mula meneroka',hint:'Pilih petak belum diteroka.',goal:n=>`Sasaran: ${n} relik`,explored:n=>`Diteroka: ${n}/20`,trap:n=>`Perangkap: ${n}`,chest:n=>`Peti: ${n}`,mapHint:'Ada peti, ada perangkap. Jawab betul untuk mendedahkannya.',shuffle:'Susun semula pulau',log:'Rekod ekspedisi',setupTitle:'Ekspedisi Relik Pulau | Tetapan',setupHelp:'Format: soalan|A|B|C|D|nombor jawapan betul. Satu soalan setiap baris.',sample:'Muat contoh',start:'Mula',correct:'Betul! Berjaya diteroka',wrong:'Salah! Perangkap aktif',win:'Relik mencukupi. Ekspedisi berjaya!',lose:'Nyawa habis. Ekspedisi gagal.',again:'Main lagi'}};const t=(k,...a)=>{const v=L[lang][k];return typeof v==='function'?v(...a):v||k};
function sample(){$('#questionText').value='AI 從什麼學習？|魔法|訓練資料|空氣|運氣|2\n保護密碼應該？|告訴朋友|寫在桌上|使用強密碼|公開分享|3\n哪一個是圖片？|photo.jpg|song.mp3|movie.mp4|note.txt|1\n可疑連結應該？|馬上點|先檢查|輸入密碼|轉發|2';}
function parse(){return $('#questionText').value.split('\n').map(r=>r.trim()).filter(Boolean).map(r=>{let p=r.split('|').map(x=>x.trim());return{q:p[0],opts:p.slice(1,5),ans:Number(p[5]||1)-1}}).filter(x=>x.q&&x.opts.length>=4)}
function makeTiles(){let types=['relic','relic','relic','key','key','chest','chest','chest','score','score','score','score','trap','trap','trap','score','key','chest','score','trap'];tiles=types.sort(()=>Math.random()-.5).map((type,i)=>({type,open:false,i}));}
function start(){qs=parse();if(!qs.length){sample();qs=parse()}target=Number($('#targetInput').value||3);lives=Number($('#lifeInput').value||5);keys=0;relics=0;score=0;logs=[];makeTiles();$('#setup').classList.add('hidden');endAt=Date.now()+Number($('#timeLimit').value||360)*1000;clearInterval(timerId);timerId=setInterval(tick,200);render()}
function tick(){let s=Math.max(0,Math.ceil((endAt-Date.now())/1000));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(s<=0)finish(false)}
function render(){$('#keys').textContent=keys;$('#relics').textContent=relics;$('#lives').textContent=lives;$('#score').textContent=score;$('#goalText').textContent=t('goal',target);$('#tilesText').textContent=t('explored',tiles.filter(x=>x.open).length);$('#dangerText').textContent=t('trap',tiles.filter(x=>x.open&&x.type==='trap').length);$('#bonusText').textContent=t('chest',tiles.filter(x=>x.open&&x.type==='chest').length);$('#map').innerHTML='';tiles.forEach(tile=>{let d=document.createElement('div');d.className='tile '+(tile.open?(tile.type==='trap'?'trap':'done'):'');let icon=tile.open?({relic:'🏺',key:'🗝️',chest:'💰',score:'⭐',trap:'🕳️'}[tile.type]):'❓';d.innerHTML='<span>'+icon+'</span><small>'+(tile.open?tile.type:'')+'</small>';d.onclick=()=>{if(!tile.open)ask(tile)};$('#map').appendChild(d)});$('#logs').innerHTML=logs.map(x=>'<div class="log">'+x+'</div>').join('')}
function ask(tile){pending=tile;let q=qs[Math.floor(Math.random()*qs.length)];pending.q=q;$('#modalTitle').textContent='🏝️';$('#modalMeta').textContent='Tile '+(tile.i+1);$('#modalQ').textContent=q.q;$('#qOptions').innerHTML='';q.opts.forEach((o,i)=>{let b=document.createElement('button');b.className='opt';b.textContent=String.fromCharCode(65+i)+'. '+o;b.onclick=()=>answer(i===q.ans);$('#qOptions').appendChild(b)});$('#quizModal').classList.remove('hidden')}
function answer(ok){$('#quizModal').classList.add('hidden');let tile=pending;if(ok){tile.open=true;if(tile.type==='relic')relics++;if(tile.type==='key')keys++;if(tile.type==='chest')score+=20;if(tile.type==='score')score+=10;if(tile.type==='trap')lives--;logs.unshift('✅ '+t('correct')+' '+({relic:'🏺',key:'🗝️',chest:'💰',score:'⭐',trap:'🕳️'}[tile.type]))}else{tile.open=true;lives--;logs.unshift('❌ '+t('wrong'))}logs=logs.slice(0,8);if(relics>=target)finish(true);else if(lives<=0)finish(false);render()}
function finish(win){clearInterval(timerId);$('#win').classList.remove('hidden');$('#winTitle').textContent=win?t('win'):t('lose');$('#winDesc').textContent='🏺 '+relics+' ｜ 🗝️ '+keys+' ｜ ⭐ '+score}
function apply(){document.title=t('title');$('#title').textContent=t('title');$('#subtitle').textContent=t('sub');$('#setupBtn').textContent=t('setup');$('#fullBtn').textContent=t('full');$('#resetBtn').textContent=t('reset');$('#statusTitle').textContent=t('status');$('#ruleTitle').textContent=t('ruleTitle');$('#ruleText').textContent=t('rule');$('#roundText').textContent=t('round');$('#hintText').textContent=t('hint');$('#mapHint').textContent=t('mapHint');$('#shuffleBtn').textContent=t('shuffle');$('#logTitle').textContent=t('log');$('#setupTitle').textContent=t('setupTitle');$('#setupHelp').textContent=t('setupHelp');$('#sampleBtn').textContent=t('sample');$('#startBtn').textContent=t('start');$('#againBtn').textContent=t('again');render()}
$('#lang').onchange=e=>{lang=e.target.value;apply()};$('#setupBtn').onclick=()=>$('#setup').classList.remove('hidden');$('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('#resetBtn').onclick=()=>location.reload();$('#sampleBtn').onclick=sample;$('#startBtn').onclick=start;$('#shuffleBtn').onclick=()=>{makeTiles();render()};sample();makeTiles();apply();
