
const I18N={
zh:{title:"关键词抢滩战",subtitle:"两队轮流抢答关键词，抢下正确词语就向沙滩推进。",setup:"设置题库",fullscreen:"全屏",restart:"重开",scoreTitle:"队伍得分",teamA:"A队",teamB:"B队",ruleTitle:"玩法说明",ruleText:"老师输入题组：题名｜提示句｜正确关键词｜全部关键词。两队轮流点击词卡；答对可抢下一块滩头并得分，答错则换对方。",round:"题组",hint:"点击正确关键词，为队伍抢下滩头。",skip:"跳过本题",next:"下一题",setupTitle:"关键词抢滩战｜老师设置",setupHelp:"每行一题，格式：题名|提示句|正确关键词1,正确关键词2|全部关键词1,全部关键词2,全部关键词3...。建议每题 6–10 个词。",sample:"载入示范",start:"开始游戏",qList:"题组清单",logTitle:"记录",turn:"当前回合",found:"已抢下",finish:"比赛结束！",again:"再玩一次",final:"最终总分",ph:"例：AI好帮手|请找出和 AI 学习有关的关键词|观察,提问,判断|观察,提问,判断,睡觉,发呆,跑步"},
en:{title:"Keyword Beachhead Battle",subtitle:"Two teams take turns to capture the correct keywords and push onto the beach.",setup:"Question settings",fullscreen:"Fullscreen",restart:"Restart",scoreTitle:"Team scores",teamA:"Team A",teamB:"Team B",ruleTitle:"How to play",ruleText:"Enter rounds in the format: title | prompt | correct keywords | all keywords. Teams tap word cards in turn. A correct answer captures beach ground and scores; a wrong answer passes the turn.",round:"Set",hint:"Tap the correct keywords to capture the beach.",skip:"Skip this set",next:"Next",setupTitle:"Keyword Beachhead Battle | Teacher Settings",setupHelp:"One round per line. Format: title|prompt|correct1,correct2|all1,all2,all3... Suggested 6–10 words per round.",sample:"Load sample",start:"Start game",qList:"Question list",logTitle:"Log",turn:"Turn",found:"Captured",finish:"Battle finished!",again:"Play again",final:"Final total score",ph:"Example: AI Helpers|Find keywords related to AI learning|observe,ask,judge|observe,ask,judge,sleep,daydream,run"},
ms:{title:"Pertempuran Pantai Kata Kunci",subtitle:"Dua kumpulan bergilir-gilir merampas kata kunci yang betul untuk mara ke pantai.",setup:"Tetapan soalan",fullscreen:"Skrin penuh",restart:"Mula semula",scoreTitle:"Markah kumpulan",teamA:"Kumpulan A",teamB:"Kumpulan B",ruleTitle:"Cara bermain",ruleText:"Masukkan set dengan format: tajuk | petunjuk | kata kunci betul | semua kata kunci. Kumpulan menekan kad kata secara bergilir. Jawapan betul merampas pantai dan mendapat markah; jawapan salah menyerahkan giliran.",round:"Set",hint:"Tekan kata kunci yang betul untuk merampas pantai.",skip:"Langkau set ini",next:"Seterusnya",setupTitle:"Pertempuran Pantai Kata Kunci | Tetapan Guru",setupHelp:"Satu set setiap baris. Format: tajuk|petunjuk|betul1,betul2|semua1,semua2,semua3... Cadangan 6–10 perkataan setiap set.",sample:"Muat contoh",start:"Mula permainan",qList:"Senarai set",logTitle:"Rekod",turn:"Giliran",found:"Dirampas",finish:"Pertempuran tamat!",again:"Main lagi",final:"Jumlah markah akhir",ph:"Contoh: AI pembantu|Cari kata kunci berkaitan pembelajaran AI|memerhati,bertanya,menilai|memerhati,bertanya,menilai,tidur,bermimpi,berlari"}
};
let lang=new URLSearchParams(location.search).get("lang")||localStorage.getItem("beach_lang")||"zh";let rounds=[],currentIndex=0,team='A',scoreA=0,scoreB=0,foundSet=new Set(),used=new Set(),logs=[],timerId=null,endAt=0;
const $=s=>document.querySelector(s);const T=k=>(I18N[lang]||I18N.zh)[k]||k;
function applyLang(){document.documentElement.lang=lang==='zh'?'zh-Hans':lang; document.title=T('title'); $('#title').textContent=T('title');$('#subtitle').textContent=T('subtitle');$('#setupBtn').textContent=T('setup');$('#fullBtn').textContent=T('fullscreen');$('#resetBtn').textContent=T('restart');$('#scoreTitle').textContent=T('scoreTitle');$('#teamALabel').textContent=T('teamA');$('#teamBLabel').textContent=T('teamB');$('#ruleTitle').textContent=T('ruleTitle');$('#ruleText').textContent=T('ruleText');$('#hintText').textContent=T('hint');$('#skipBtn').textContent=T('skip');$('#nextBtn').textContent=T('next');$('#setupTitle').textContent=T('setupTitle');$('#setupHelp').textContent=T('setupHelp');$('#sampleBtn').textContent=T('sample');$('#startBtn').textContent=T('start');$('#qListTitle').textContent=T('qList');$('#logTitle').textContent=T('logTitle');$('#winTitle').textContent=T('finish');$('#againBtn').textContent=T('again');$('#roundTextArea').placeholder=T('ph');$('#lang').value=lang;$('#setupLang').value=lang;render();}
function sample(){const s=lang==='en'
?`AI Helpers|Find keywords related to AI learning|observe,ask,judge|observe,ask,judge,sleep,daydream,run,collect,analyse
Cyber Safety|Find actions that keep your account safe|strong password,logout,check link|strong password,logout,check link,share password,click all links,post ID card`
:lang==='ms'
?`Pembantu AI|Cari kata kunci berkaitan pembelajaran AI|memerhati,bertanya,menilai|memerhati,bertanya,menilai,tidur,bermimpi,berlari,mengumpul,menganalisis
Keselamatan Siber|Cari tindakan yang menjaga akaun anda|kata laluan kuat,log keluar,semak pautan|kata laluan kuat,log keluar,semak pautan,kongsi kata laluan,klik semua pautan,siar kad pengenalan`
:`AI好帮手|请找出和 AI 学习有关的关键词|观察,提问,判断|观察,提问,判断,睡觉,发呆,跑步,收集,分析
网络安全|请找出保护账号安全的做法|强密码,登出,检查链接|强密码,登出,检查链接,分享密码,乱点链接,公开身份证`;
$('#roundTextArea').value=s;}
function parse(){const rows=$('#roundTextArea').value.split('\n').map(x=>x.trim()).filter(Boolean); return rows.map(row=>{const p=row.split('|').map(x=>x.trim()); const title=p[0]||'Q'; const prompt=p[1]||''; const correct=(p[2]||'').split(',').map(x=>x.trim()).filter(Boolean); let all=(p[3]||'').split(',').map(x=>x.trim()).filter(Boolean); if(!all.length) all=[...correct,'A','B','C']; all=[...new Set([...all,...correct])].sort(()=>Math.random()-.5); return {title,prompt,correct,all};}).filter(x=>x.correct.length>=2 && x.all.length>=4);}
function start(){rounds=parse(); if(!rounds.length){sample(); rounds=parse();} currentIndex=0; team='A'; scoreA=0; scoreB=0; logs=[]; $('#setup').classList.add('hidden'); endAt=Date.now()+Number($('#timeLimit').value||300)*1000; clearInterval(timerId); timerId=setInterval(tick,200); loadRound(0);}
function tick(){const left=Math.max(0,endAt-Date.now()); const s=Math.ceil(left/1000); $('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; if(left<=0)finish();}
function loadRound(i){currentIndex=i; foundSet=new Set(); used=new Set(); team='A'; render();}
function render(){if(!rounds.length){$('#promptTitle').textContent=''; $('#promptText').textContent=''; return;} const r=rounds[currentIndex]; $('#promptTitle').textContent=r.title; $('#promptText').textContent=r.prompt; $('#roundText').textContent=`${T('round')}：${currentIndex+1}/${rounds.length}`; $('#scoreA').textContent=scoreA; $('#scoreB').textContent=scoreB; $('#turnChip').textContent=`${T('turn')}：${team==='A'?T('teamA'):T('teamB')}`; $('#foundChip').textContent=`${T('found')}：${foundSet.size}/${r.correct.length}`; const pctA=(scoreA+scoreB)?scoreA/(scoreA+scoreB)*100:50; $('#waveA').style.width=pctA+'%'; $('#waveB').style.width=(100-pctA)+'%'; const grid=$('#wordGrid'); grid.innerHTML=''; r.all.forEach(w=>{const d=document.createElement('div'); const owner=[...used].find(x=>x.split('::')[0]===w)?.split('::')[1]||''; d.className='word'+(usedHas(w)?' used':'')+(owner?' '+owner.toLowerCase():''); d.textContent=w; d.onclick=()=>pickWord(w); grid.appendChild(d);}); $('#questionList').innerHTML=rounds.map((q,i)=>`<div class="q-pill ${i===currentIndex?'active':''}">${i+1}. ${q.title}<br><span>${q.correct.length} keywords</span></div>`).join(''); $('#logs').innerHTML=logs.map(x=>`<div class="log">${x}</div>`).join('');}
function usedHas(word){return [...used].some(x=>x.split('::')[0]===word);}
function pickWord(word){const r=rounds[currentIndex]; if(usedHas(word)) return; used.add(word+'::'+team); if(r.correct.includes(word)){foundSet.add(word); if(team==='A') scoreA+=10; else scoreB+=10; logs.unshift(`✅ ${team==='A'?T('teamA'):T('teamB')}：${word}`); if(foundSet.size===r.correct.length){$('#nextBtn').classList.remove('hidden'); logs.unshift('🏁 '+r.title+'｜'+T('found')+` ${foundSet.size}/${r.correct.length}`);} } else {logs.unshift(`❌ ${team==='A'?T('teamA'):T('teamB')}：${word}`); team=(team==='A'?'B':'A');} logs=logs.slice(0,8); render();}
function nextRound(){if(currentIndex<rounds.length-1){$('#nextBtn').classList.add('hidden'); loadRound(currentIndex+1);} else finish();}
function skipRound(){team=(team==='A'?'B':'A'); logs.unshift(`↔️ ${T('turn')}：${team==='A'?T('teamA'):T('teamB')}`); logs=logs.slice(0,8); render();}
function finish(){clearInterval(timerId); const winner=scoreA===scoreB?'Draw':(scoreA>scoreB?T('teamA'):T('teamB')); $('#winDesc').textContent=`${T('final')}：${T('teamA')} ${scoreA} ｜ ${T('teamB')} ${scoreB} ｜ Winner: ${winner}`; $('#win').classList.remove('hidden');}
$('#lang').onchange=e=>{lang=e.target.value; localStorage.setItem('beach_lang',lang); applyLang();}; $('#setupLang').onchange=e=>{lang=e.target.value; localStorage.setItem('beach_lang',lang); applyLang();};
$('#setupBtn').onclick=()=>$('#setup').classList.remove('hidden'); $('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.(); $('#resetBtn').onclick=()=>location.reload(); $('#sampleBtn').onclick=sample; $('#startBtn').onclick=start; $('#skipBtn').onclick=skipRound; $('#nextBtn').onclick=nextRound;
sample(); applyLang();
