
const I18N={
zh:{title:"王国资源争夺战",subtitle:"两国争夺农田、森林与金矿，答对题目才能占领资源点。",setup:"设置题库",fullscreen:"全屏",restart:"重开",scoreTitle:"王国得分",teamA:"蓝色王国",teamB:"橙色王国",ruleTitle:"玩法说明",ruleText:"三条资源路线分别提供粮食、木材与黄金。轮到某队时，可点选自己边界旁的可争夺资源点；答对题目即可占领并获得资源分。先达目标分，或回合结束时分数较高者获胜。",round:"回合",hint:"请选择发光的可占领资源点。",boardTitle:"中央资源地带",castleA:"蓝色王国",castleB:"橙色王国",resource:"资源收益",food:"农田",wood:"森林",gold:"金矿",setupTitle:"王国资源争夺战｜老师设置",setupHelp:"题库格式：题目|选项A|选项B|选项C|选项D|正确答案编号(1-4)。系统会随机抽题。",sample:"载入示范",start:"开始游戏",logTitle:"战况记录",turn:"当前行动",target:"目标分",turnLimit:"总回合",timeLimit:"时间",questionOf:"正在争夺",finish:"战争结束！",again:"再玩一次",final:"最终结果",correct:"答对，占领成功！",wrong:"答错，资源点仍保持中立。"},
en:{title:"Kingdom Resource Battle",subtitle:"Two kingdoms fight for farms, forests and gold mines. Answer correctly to capture resources.",setup:"Question settings",fullscreen:"Fullscreen",restart:"Restart",scoreTitle:"Kingdom scores",teamA:"Blue Kingdom",teamB:"Orange Kingdom",ruleTitle:"How to play",ruleText:"Three lanes provide food, wood and gold. On a team's turn, click a glowing claimable resource next to your frontier. Answer correctly to capture it and earn points. First to the target score, or the higher score when turns end, wins.",round:"Turn",hint:"Choose one of the glowing claimable resource nodes.",boardTitle:"Central resource zone",castleA:"Blue Kingdom",castleB:"Orange Kingdom",resource:"Resource values",food:"Farm",wood:"Forest",gold:"Gold mine",setupTitle:"Kingdom Resource Battle | Teacher Settings",setupHelp:"Question bank format: question|option A|option B|option C|option D|correct answer number (1-4). Questions are drawn randomly.",sample:"Load sample",start:"Start game",logTitle:"Battle log",turn:"Current action",target:"Target score",turnLimit:"Total turns",timeLimit:"Time",questionOf:"Capturing",finish:"War ended!",again:"Play again",final:"Final result",correct:"Correct! Resource captured.",wrong:"Wrong answer. The node remains neutral."},
ms:{title:"Pertempuran Sumber Kerajaan",subtitle:"Dua kerajaan berebut ladang, hutan dan lombong emas. Jawab betul untuk menawan sumber.",setup:"Tetapan soalan",fullscreen:"Skrin penuh",restart:"Mula semula",scoreTitle:"Markah kerajaan",teamA:"Kerajaan Biru",teamB:"Kerajaan Oren",ruleTitle:"Cara bermain",ruleText:"Tiga laluan sumber menyediakan makanan, kayu dan emas. Apabila tiba giliran sesuatu pasukan, klik nod sumber bercahaya di sempadan sendiri. Jawab betul untuk menawan nod dan memperoleh mata. Kerajaan yang mencapai sasaran terlebih dahulu, atau markah lebih tinggi apabila pusingan tamat, menang.",round:"Pusingan",hint:"Pilih nod sumber bercahaya yang boleh dirampas.",boardTitle:"Zon sumber tengah",castleA:"Kerajaan Biru",castleB:"Kerajaan Oren",resource:"Nilai sumber",food:"Ladang",wood:"Hutan",gold:"Lombong emas",setupTitle:"Pertempuran Sumber Kerajaan | Tetapan Guru",setupHelp:"Format bank soalan: soalan|pilihan A|pilihan B|pilihan C|pilihan D|nombor jawapan betul (1-4). Soalan dipilih secara rawak.",sample:"Muat contoh",start:"Mula permainan",logTitle:"Rekod pertempuran",turn:"Tindakan semasa",target:"Markah sasaran",turnLimit:"Jumlah pusingan",timeLimit:"Masa",questionOf:"Sedang merampas",finish:"Perang tamat!",again:"Main lagi",final:"Keputusan akhir",correct:"Betul! Sumber berjaya dirampas.",wrong:"Jawapan salah. Nod kekal neutral."}
};
let lang=new URLSearchParams(location.search).get("lang")||localStorage.getItem("kingdom_lang")||"zh";
const laneInfo=[{id:'food',value:1,icon:'🌾'},{id:'wood',value:2,icon:'🌲'},{id:'gold',value:3,icon:'⛏️'}];
let questions=[],nodes=[],turn='A',turnCount=1,turnLimit=18,targetScore=20,scoreA=0,scoreB=0,timerId=null,endAt=0,logs=[],pending=null;
const $=s=>document.querySelector(s);const T=k=>(I18N[lang]||I18N.zh)[k]||k;
function applyLang(){document.documentElement.lang=lang==='zh'?'zh-Hans':lang;document.title=T('title');$('#title').textContent=T('title');$('#subtitle').textContent=T('subtitle');$('#setupBtn').textContent=T('setup');$('#fullBtn').textContent=T('fullscreen');$('#resetBtn').textContent=T('restart');$('#scoreTitle').textContent=T('scoreTitle');$('#teamALabel').textContent=T('teamA');$('#teamBLabel').textContent=T('teamB');$('#ruleTitle').textContent=T('ruleTitle');$('#ruleText').textContent=T('ruleText');$('#hintText').textContent=T('hint');$('#boardTitle').textContent=T('boardTitle');$('#castleATitle').textContent=T('castleA');$('#castleBTitle').textContent=T('castleB');$('#resourceTitle').textContent=T('resource');$('#logTitle').textContent=T('logTitle');$('#setupTitle').textContent=T('setupTitle');$('#setupHelp').textContent=T('setupHelp');$('#sampleBtn').textContent=T('sample');$('#startBtn').textContent=T('start');$('#winTitle').textContent=T('finish');$('#againBtn').textContent=T('again'); render();}
function sample(){const s=lang==='en'
?`Which password is safer?|123456|myname|BlueSky!2026|birthday|3
Which action protects your privacy?|Share ID card|Log out after use|Post phone number|Click any link|2
AI learns from what?|training data|magic|guessing only|nothing|1
Which file is an image?|photo.jpg|essay.docx|music.mp3|video.mp4|1
What should you do before trusting information?|Forward immediately|Check source|Change nothing|Ignore everything|2`
:lang==='ms'
?`Kata laluan manakah lebih selamat?|123456|namasaya|LangitBiru!2026|tarikh lahir|3
Tindakan manakah melindungi privasi?|Kongsi kad pengenalan|Log keluar selepas guna|Siarkan nombor telefon|Klik semua pautan|2
AI belajar daripada apa?|data latihan|sihir|tekaan sahaja|tiada apa-apa|1
Fail manakah ialah gambar?|photo.jpg|essay.docx|music.mp3|video.mp4|1
Apa yang perlu dibuat sebelum mempercayai maklumat?|Terus kongsi|Semak sumber|Jangan ubah apa-apa|Abaikan semua|2`
:`哪一个密码比较安全？|123456|我的名字|BlueSky!2026|生日|3
哪一种做法能保护隐私？|分享身份证|使用后登出|公开电话号码|随便点链接|2
AI 从什么学习？|训练数据|魔法|只靠猜测|什么都不需要|1
哪一个文件是图片？|photo.jpg|essay.docx|music.mp3|video.mp4|1
在相信资讯前应该做什么？|马上转发|检查来源|什么都不做|全部忽略|2`;
$('#questionText').value=s;}
function parseQuestions(){const rows=$('#questionText').value.split('\n').map(x=>x.trim()).filter(Boolean);return rows.map(r=>{const p=r.split('|').map(x=>x.trim());return{q:p[0]||'',opts:p.slice(1,5),answer:Number(p[5]||1)-1};}).filter(x=>x.q && x.opts.length>=4);}
function initNodes(){nodes=laneInfo.map((lane,li)=>Array.from({length:5},(_,ni)=>({lane:li,index:ni,owner:null,value:lane.value,icon:lane.icon}))); }
function start(){questions=parseQuestions();if(!questions.length){sample();questions=parseQuestions();}turn='A';turnCount=1;turnLimit=Number($('#turnLimit').value||18);targetScore=Number($('#targetScore').value||20);scoreA=0;scoreB=0;logs=[];initNodes();$('#setup').classList.add('hidden');endAt=Date.now()+Number($('#timeLimit').value||360)*1000;clearInterval(timerId);timerId=setInterval(tick,200);render();}
function tick(){const left=Math.max(0,endAt-Date.now());const s=Math.ceil(left/1000);$('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; if(left<=0)finish();}
function isSelectable(node){if(node.owner) return false; if(turn==='A'){return node.index===0 || nodes[node.lane][node.index-1].owner==='A';} return node.index===4 || nodes[node.lane][node.index+1].owner==='B';}
function render(){ $('#scoreA').textContent=scoreA; $('#scoreB').textContent=scoreB; $('#castleAScore').textContent=`${scoreA} pts`; $('#castleBScore').textContent=`${scoreB} pts`; $('#roundText').textContent=`${T('round')}：${turnCount}/${turnLimit} ｜ ${T('turn')}：${turn==='A'?T('teamA'):T('teamB')}`; const lanes=$('#lanes'); lanes.innerHTML=''; laneInfo.forEach((lane,li)=>{const row=document.createElement('div');row.className='lane'; row.innerHTML=`<div class="laneTitle">${T(lane.id)}<br><small>+${lane.value}</small></div>`; nodes[li].forEach(node=>{const d=document.createElement('div'); d.className='node'+(node.owner?' '+node.owner.toLowerCase():'')+(isSelectable(node)?' selectable':''); d.innerHTML=`<div>${lane.icon}<br><small>${T(lane.id)}</small></div><div class="value">+${node.value}</div>`; d.onclick=()=>{if(isSelectable(node))openQuestion(node);}; row.appendChild(d);}); lanes.appendChild(row);}); $('#resourceList').innerHTML=laneInfo.map(l=>`<div class="res">${l.icon} ${T(l.id)}：+${l.value} pts</div>`).join(''); $('#logs').innerHTML=logs.map(x=>`<div class="log">${x}</div>`).join('');}
function openQuestion(node){pending=node; const q=questions[Math.floor(Math.random()*questions.length)]; pending.q=q; $('#qModalTitle').textContent=`${T('questionOf')} ${T(laneInfo[node.lane].id)} +${node.value}`; $('#qModalMeta').textContent=`${turn==='A'?T('teamA'):T('teamB')} ｜ Lane ${node.lane+1}`; $('#qModalPrompt').textContent=q.q; $('#qOptions').innerHTML=''; q.opts.forEach((opt,idx)=>{const b=document.createElement('button'); b.className='opt'; b.textContent=`${String.fromCharCode(65+idx)}. ${opt}`; b.onclick=()=>answer(idx); $('#qOptions').appendChild(b);}); $('#quizModal').classList.remove('hidden');}
function answer(idx){const node=pending; const correct=idx===node.q.answer; if(correct){node.owner=turn; if(turn==='A')scoreA+=node.value; else scoreB+=node.value; logs.unshift(`✅ ${turn==='A'?T('teamA'):T('teamB')}｜${T(laneInfo[node.lane].id)} +${node.value}`);} else {logs.unshift(`❌ ${turn==='A'?T('teamA'):T('teamB')}｜${T('wrong')}`);} logs=logs.slice(0,10); $('#quizModal').classList.add('hidden'); pending=null; if(scoreA>=targetScore || scoreB>=targetScore){finish(); return;} if(allClaimed()){finish(); return;} turn=(turn==='A'?'B':'A'); turnCount++; if(turnCount>turnLimit){finish(); return;} render();}
function allClaimed(){return nodes.flat().every(n=>n.owner);}
function finish(){clearInterval(timerId); const winner=scoreA===scoreB?'Draw':(scoreA>scoreB?T('teamA'):T('teamB')); $('#winDesc').textContent=`${T('final')}：${T('teamA')} ${scoreA} ｜ ${T('teamB')} ${scoreB} ｜ Winner: ${winner}`; $('#win').classList.remove('hidden');}
$('#lang').onchange=e=>{lang=e.target.value; localStorage.setItem('kingdom_lang',lang); applyLang();}; $('#setupLang').onchange=e=>{lang=e.target.value; localStorage.setItem('kingdom_lang',lang); applyLang();};
$('#setupBtn').onclick=()=>$('#setup').classList.remove('hidden'); $('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.(); $('#resetBtn').onclick=()=>location.reload(); $('#sampleBtn').onclick=sample; $('#startBtn').onclick=start;
sample(); applyLang();
