
const $=s=>document.querySelector(s);
let lang='zh', setupQuestions=[], questions=[], current=0, teamCount=2, teams=[], pointValue=10, revealed=[], revealTimer=null, endAt=0, timerId=null, buzzedTeam=null, logs=[], roundDone=false, imageRatio=1.4;
const L={
 zh:{title:'看圖猜生字',sub:'圖片 5×5 逐步揭開，分組搶答猜出生字。',setup:'設定題庫',full:'全屏',reset:'重開',score:'隊伍分數',ruleTitle:'玩法說明',rule:'老師上傳圖片與答案。圖片會切成 5×5，每 3 秒隨機揭開一片。學生按下搶答後，由老師判斷正確或錯誤。答錯可繼續搶答。',ready:'準備開始',hint:'等待圖片逐步揭開，學生可隨時搶答。',qTitle:'看圖猜生字',qList:'題目清單',log:'搶答記錄',setupTitle:'看圖猜生字｜老師設定',setupHelp:'每題上傳一張圖片，並輸入答案。遊戲會把圖片切成 5×5，開始後每 3 秒自動隨機揭開一片。',add:'新增題目',sample:'載入示範',start:'開始遊戲',correct:'正確，加分',wrong:'錯誤，繼續搶答',show:'顯示答案',next:'下一題',again:'再玩一次',team:n=>`第 ${n} 組`,round:(a,b)=>`第 ${a} 題 / 共 ${b} 題`,answer:a=>`答案：${a}`,buzz:n=>`第 ${n} 組搶答！`,ok:(n,p)=>`第 ${n} 組答對 +${p}`,bad:n=>`第 ${n} 組答錯，繼續搶答`,finish:'遊戲結束',upload:'上傳圖片',ans:'答案 / 生字',remove:'刪除'},
 en:{title:'Picture Word Guess',sub:'A 5×5 image reveal game. Teams buzz in to guess the word.',setup:'Questions',full:'Fullscreen',reset:'Restart',score:'Team scores',ruleTitle:'How to play',rule:'Teachers upload an image and answer. The image is split into 5×5 tiles. Every 3 seconds, a random tile is revealed. Teams buzz in; the teacher judges correct or wrong. Wrong answers can continue.',ready:'Ready',hint:'Wait for tiles to reveal. Teams may buzz anytime.',qTitle:'Picture Word Guess',qList:'Question list',log:'Buzz log',setupTitle:'Picture Word Guess | Teacher Settings',setupHelp:'Upload one image and enter the answer for each question. The image is split into 5×5 and reveals one random tile every 3 seconds.',add:'Add question',sample:'Load sample',start:'Start game',correct:'Correct, score',wrong:'Wrong, continue',show:'Show answer',next:'Next',again:'Play again',team:n=>`Team ${n}`,round:(a,b)=>`Question ${a} / ${b}`,answer:a=>`Answer: ${a}`,buzz:n=>`Team ${n} buzzed!`,ok:(n,p)=>`Team ${n} correct +${p}`,bad:n=>`Team ${n} wrong, continue`,finish:'Game over',upload:'Upload image',ans:'Answer / word',remove:'Remove'},
 ms:{title:'Teka Perkataan Melalui Gambar',sub:'Gambar 5×5 dibuka sedikit demi sedikit. Kumpulan menekan buzzer untuk meneka.',setup:'Soalan',full:'Skrin penuh',reset:'Mula semula',score:'Markah kumpulan',ruleTitle:'Cara bermain',rule:'Guru memuat naik gambar dan jawapan. Gambar dipotong 5×5. Setiap 3 saat, satu bahagian dibuka secara rawak. Kumpulan menekan buzzer dan guru menilai betul atau salah. Jawapan salah boleh terus rebut.',ready:'Sedia',hint:'Tunggu bahagian gambar dibuka. Kumpulan boleh rebut bila-bila masa.',qTitle:'Teka perkataan',qList:'Senarai soalan',log:'Rekod rebut',setupTitle:'Teka Perkataan Melalui Gambar | Tetapan Guru',setupHelp:'Muat naik satu gambar dan masukkan jawapan untuk setiap soalan. Gambar dipotong 5×5 dan dibuka satu bahagian setiap 3 saat.',add:'Tambah soalan',sample:'Muat contoh',start:'Mula permainan',correct:'Betul, tambah markah',wrong:'Salah, terus rebut',show:'Papar jawapan',next:'Seterusnya',again:'Main lagi',team:n=>`Kumpulan ${n}`,round:(a,b)=>`Soalan ${a} / ${b}`,answer:a=>`Jawapan: ${a}`,buzz:n=>`Kumpulan ${n} menekan buzzer!`,ok:(n,p)=>`Kumpulan ${n} betul +${p}`,bad:n=>`Kumpulan ${n} salah, terus rebut`,finish:'Permainan tamat',upload:'Muat naik gambar',ans:'Jawapan / perkataan',remove:'Buang'}
};
const t=(k,...a)=>{const v=(L[lang]||L.zh)[k];return typeof v==='function'?v(...a):v||k};
function sampleSvg(word,i){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="620"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${i%2?'#0f766e':'#1d4ed8'}"/><stop offset="1" stop-color="#0f172a"/></linearGradient></defs><rect width="900" height="620" rx="30" fill="url(#g)"/><circle cx="230" cy="220" r="95" fill="#facc15"/><rect x="430" y="160" width="250" height="180" rx="30" fill="#38bdf8"/><path d="M220 420 C350 300 500 520 690 360" stroke="#22c55e" stroke-width="38" fill="none" stroke-linecap="round"/><text x="450" y="560" text-anchor="middle" fill="white" font-family="Arial,Microsoft YaHei" font-size="52" font-weight="900">${word}</text></svg>`;return 'data:image/svg+xml,'+encodeURIComponent(svg)}
function loadSample(){setupQuestions=[{title:'太陽',answer:'日',image:sampleSvg('日',0)},{title:'月亮',answer:'月',image:sampleSvg('月',1)},{title:'山峰',answer:'山',image:sampleSvg('山',2)}];renderEditors()}
function addQuestion(){setupQuestions.push({title:'',answer:'',image:sampleSvg('?',setupQuestions.length)});renderEditors()}
function removeQuestion(i){setupQuestions.splice(i,1);renderEditors()}
function readFile(f,cb){const r=new FileReader();r.onload=e=>cb(e.target.result);r.readAsDataURL(f)}
function renderEditors(){const box=$('#editorList');box.innerHTML='';setupQuestions.forEach((q,i)=>{const d=document.createElement('div');d.className='q-editor';d.innerHTML=`<div class="q-editor-head"><b>Q${i+1}</b><button class="btn small secondary rm">${t('remove')}</button></div><div class="q-editor-body"><div class="uploadbox"><input class="input titleInput" value="${(q.title||'').replaceAll('"','&quot;')}" placeholder="${t('qTitle')}"><input class="input answerInput" value="${(q.answer||'').replaceAll('"','&quot;')}" placeholder="${t('ans')}"><label class="help">${t('upload')}</label><input class="input fileInput" type="file" accept="image/*"></div><div class="preview"><img src="${q.image||''}" alt=""></div></div>`;box.appendChild(d);d.querySelector('.rm').onclick=()=>removeQuestion(i);d.querySelector('.titleInput').oninput=e=>q.title=e.target.value;d.querySelector('.answerInput').oninput=e=>q.answer=e.target.value;d.querySelector('.fileInput').onchange=e=>{const f=e.target.files[0];if(f)readFile(f,src=>{q.image=src;renderEditors()})};})}
function apply(){document.documentElement.lang=lang==='zh'?'zh-Hans':lang;document.title=t('title');$('#title').textContent=t('title');$('#subtitle').textContent=t('sub');$('#setupBtn').textContent=t('setup');$('#fullBtn').textContent=t('full');$('#resetBtn').textContent=t('reset');$('#scoreTitle').textContent=t('score');$('#ruleTitle').textContent=t('ruleTitle');$('#ruleText').textContent=t('rule');$('#roundText').textContent=t('ready');$('#hintText').textContent=t('hint');$('#questionTitle').textContent=t('qTitle');$('#qListTitle').textContent=t('qList');$('#logTitle').textContent=t('log');$('#setupTitle').textContent=t('setupTitle');$('#setupHelp').textContent=t('setupHelp');$('#addQuestionBtn').textContent=t('add');$('#sampleBtn').textContent=t('sample');$('#startBtn').textContent=t('start');$('#correctBtn').textContent=t('correct');$('#wrongBtn').textContent=t('wrong');$('#showAnswerBtn').textContent=t('show');$('#nextBtn').textContent=t('next');$('#againBtn').textContent=t('again');renderEditors();renderTeams();renderList()}
function start(){questions=setupQuestions.filter(q=>q.image&&q.answer).map(q=>({...q}));if(!questions.length){loadSample();questions=setupQuestions.map(q=>({...q}))}teamCount=Number($('#teamCount').value||2);pointValue=Number($('#pointValue').value||10);teams=Array.from({length:teamCount},(_,i)=>({name:t('team',i+1),score:0}));current=0;logs=[];$('#setup').classList.add('hidden');endAt=Date.now()+Number($('#timeLimit').value||300)*1000;clearInterval(timerId);timerId=setInterval(tick,200);loadRound(0)}
function tick(){const s=Math.max(0,Math.ceil((endAt-Date.now())/1000));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(s<=0)finish()}
function loadRound(i){current=i;revealed=new Array(25).fill(false);buzzedTeam=null;roundDone=false;$('#judgeBox').classList.add('hidden');$('#nextBtn').classList.add('hidden');$('#answerText').classList.add('hidden');setImageRatio(questions[current].image);buildGrid();renderRound();clearInterval(revealTimer);revealOne();revealTimer=setInterval(revealOne,3000)}
function setImageRatio(src){const img=new Image();img.onload=()=>{imageRatio=img.naturalWidth/img.naturalHeight;resizeGrid()};img.src=src;setTimeout(resizeGrid,50)}
function resizeGrid(){const grid=$('#puzzleGrid');const wrap=$('#puzzleStage');const w=wrap.clientWidth,h=wrap.clientHeight;let gw=w,gh=w/(imageRatio||1.4);if(gh>h){gh=h;gw=h*(imageRatio||1.4)}grid.style.width=gw+'px';grid.style.height=gh+'px'}
window.addEventListener('resize',resizeGrid);
function buildGrid(){const grid=$('#puzzleGrid');grid.innerHTML='';for(let r=0;r<5;r++){for(let c=0;c<5;c++){const idx=r*5+c;const d=document.createElement('div');d.className='tile hidden-tile';d.dataset.idx=idx;d.style.backgroundImage=`url("${questions[current].image}")`;d.style.backgroundSize='500% 500%';d.style.backgroundPosition=`${c*25}% ${r*25}%`;grid.appendChild(d)}}resizeGrid()}
function revealOne(){if(roundDone)return;const closed=revealed.map((v,i)=>v?null:i).filter(v=>v!==null);if(!closed.length)return;const idx=closed[Math.floor(Math.random()*closed.length)];revealed[idx]=true;const tile=$(`#puzzleGrid .tile[data-idx="${idx}"]`);if(tile){tile.classList.remove('hidden-tile');tile.classList.add('revealed','flash');setTimeout(()=>tile.classList.remove('flash'),700)}renderRound()}
function renderRound(){$('#roundText').textContent=t('round',current+1,questions.length);$('#questionTitle').textContent=questions[current]?.title||t('qTitle');$('#answerText').textContent=t('answer',questions[current]?.answer||'');renderTeams();renderList();renderLogs();renderBuzzers()}
function renderTeams(){const box=$('#teamList');box.innerHTML='';(teams.length?teams:Array.from({length:Number($('#teamCount')?.value||2)},(_,i)=>({name:t('team',i+1),score:0}))).forEach((tm,i)=>{const d=document.createElement('div');d.className='team-card'+(buzzedTeam===i?' active':'');d.innerHTML=`<span>${t('team',i+1)}</span><span class="team-score">${tm.score}</span>`;box.appendChild(d)})}
function renderBuzzers(){const row=$('#buzzerRow');row.innerHTML='';for(let i=0;i<teamCount;i++){const b=document.createElement('button');b.className='buzzer t'+(i+1);b.textContent=t('team',i+1);b.disabled=buzzedTeam!==null||roundDone;b.onclick=()=>buzz(i);row.appendChild(b)}}
function buzz(i){buzzedTeam=i;logs.unshift('🔔 '+t('buzz',i+1));logs=logs.slice(0,10);$('#judgeTeam').textContent=t('buzz',i+1);$('#judgeBox').classList.remove('hidden');renderRound()}
function markCorrect(){if(buzzedTeam===null)return;teams[buzzedTeam].score+=pointValue;logs.unshift('✅ '+t('ok',buzzedTeam+1,pointValue));logs=logs.slice(0,10);roundDone=true;clearInterval(revealTimer);revealed.fill(true);document.querySelectorAll('.tile').forEach(t=>t.classList.remove('hidden-tile'));$('#nextBtn').classList.remove('hidden');renderRound()}
function markWrong(){if(buzzedTeam===null)return;logs.unshift('❌ '+t('bad',buzzedTeam+1));logs=logs.slice(0,10);buzzedTeam=null;$('#judgeBox').classList.add('hidden');renderRound()}
function showAnswer(){$('#answerText').classList.toggle('hidden')}
function nextRound(){if(current<questions.length-1)loadRound(current+1);else finish()}
function renderList(){$('#questionList').innerHTML=(questions.length?questions:setupQuestions).map((q,i)=>`<div class="q-pill ${i===current&&questions.length?'active':''} ${questions.length&&i<current?'done':''}">Q${i+1}｜${q.title||t('qTitle')}<br><span>${q.answer||''}</span></div>`).join('')}
function renderLogs(){$('#logs').innerHTML=logs.map(x=>`<div class="log">${x}</div>`).join('')}
function finish(){clearInterval(timerId);clearInterval(revealTimer);$('#win').classList.remove('hidden');$('#winTitle').textContent=t('finish');const sorted=[...teams].map((x,i)=>({...x,i})).sort((a,b)=>b.score-a.score);$('#winDesc').textContent=sorted.map(x=>`${t('team',x.i+1)}：${x.score}`).join(' ｜ ')}
$('#lang').onchange=e=>{lang=e.target.value;apply()};$('#setupLang').onchange=e=>{lang=e.target.value;apply()};$('#setupBtn').onclick=()=>$('#setup').classList.remove('hidden');$('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('#resetBtn').onclick=()=>location.reload();$('#addQuestionBtn').onclick=addQuestion;$('#sampleBtn').onclick=loadSample;$('#startBtn').onclick=start;$('#correctBtn').onclick=markCorrect;$('#wrongBtn').onclick=markWrong;$('#showAnswerBtn').onclick=showAnswer;$('#nextBtn').onclick=nextRound;
loadSample();apply();
