
const I18N={
 zh:{title:'句子排序挑战',subtitle:'把词语、句子或步骤排回正确顺序',uiLang:'介面语言',teamCount:'队伍数量',gameTime:'游戏时间',targetScore:'目标分',questionMode:'出题方式',wrongPenalty:'答错扣分',rightTurn:'答对后',wrongTurn:'答错后',showAnswer:'答错显示答案',sound:'音效',questionBank:'题库设定',formatHint:'格式：提示 | 正确顺序。项目请用 / 分隔。例如：AI流程 | 收集资料 / 标注图片 / 训练模型 / 测试模型。',importTxt:'汇入 TXT',exportTxt:'导出 TXT',loadSample:'载入范例',startGame:'开始游戏',round:'回合',showSettings:'显示老师设定',fullscreen:'全屏',nextQuestion:'下一题',reset:'重置',currentQuestion:'当前题目',currentTeam:'当前队伍',readyMsg:'准备开始。老师点击“开始游戏”后，设定区会隐藏。',answerArea:'答案排序区',wordBank:'词语卡片区',clickTip:'点击或拖动卡片来排序',clearAnswer:'清空答案',submitAnswer:'提交答案',close:'关闭',playAgain:'再玩一次',teamRed:'红队',teamBlue:'蓝队',teamGreen:'绿队',teamPurple:'紫队',unlimited:'不限时',min3:'3 分钟',min5:'5 分钟',min8:'8 分钟',min10:'10 分钟',random:'随机',order:'顺序',yes:'是',no:'否',show:'显示',hide:'不显示',on:'开启',off:'关闭',next:'换下一队',same:'本队继续',needStart:'请先点击开始游戏。',bankError:'题库至少需要 1 题，每题至少 2 个排序项目。',notFull:'还没有排完整。',correct:'答对了！排序正确。',wrong:'答错了！',correctAnswer:'正确顺序：',gameOver:'游戏结束',winner:'获胜队伍',timeUp:'时间到！',targetReached:'达到目标分！',question:'题目',score:'分数',rank:'排名',loaded:'已载入题库。',settingsShown:'老师设定区已显示。',settingsHidden:'老师设定区已隐藏。',noQuestion:'没有可用题目。'},
 en:{title:'Sentence Order Challenge',subtitle:'Put words, sentences, or steps back in the correct order',uiLang:'UI Language',teamCount:'Number of Teams',gameTime:'Game Time',targetScore:'Target Score',questionMode:'Question Mode',wrongPenalty:'Wrong Answer Penalty',rightTurn:'After Correct',wrongTurn:'After Wrong',showAnswer:'Show Answer After Wrong',sound:'Sound',questionBank:'Question Bank',formatHint:'Format: Prompt | Correct order. Use / to separate items. Example: AI Process | Collect data / Label images / Train model / Test model.',importTxt:'Import TXT',exportTxt:'Export TXT',loadSample:'Load Sample',startGame:'Start Game',round:'Round',showSettings:'Show Teacher Settings',fullscreen:'Fullscreen',nextQuestion:'Next Question',reset:'Reset',currentQuestion:'Current Question',currentTeam:'Current Team',readyMsg:'Ready. After the teacher clicks Start Game, the settings panel will be hidden.',answerArea:'Answer Order Area',wordBank:'Word Card Area',clickTip:'Click or drag cards to arrange',clearAnswer:'Clear Answer',submitAnswer:'Submit Answer',close:'Close',playAgain:'Play Again',teamRed:'Red Team',teamBlue:'Blue Team',teamGreen:'Green Team',teamPurple:'Purple Team',unlimited:'Unlimited',min3:'3 minutes',min5:'5 minutes',min8:'8 minutes',min10:'10 minutes',random:'Random',order:'In order',yes:'Yes',no:'No',show:'Show',hide:'Hide',on:'On',off:'Off',next:'Next team',same:'Same team continues',needStart:'Please start the game first.',bankError:'The bank needs at least 1 question, and each question needs at least 2 items.',notFull:'The answer is not complete yet.',correct:'Correct! The order is right.',wrong:'Wrong order!',correctAnswer:'Correct order: ',gameOver:'Game Over',winner:'Winner',timeUp:'Time is up!',targetReached:'Target score reached!',question:'Question',score:'Score',rank:'Rank',loaded:'Question bank loaded.',settingsShown:'Teacher settings are shown.',settingsHidden:'Teacher settings are hidden.',noQuestion:'No available question.'},
 ms:{title:'Cabaran Susun Ayat',subtitle:'Susun perkataan, ayat atau langkah mengikut urutan yang betul',uiLang:'Bahasa Antara Muka',teamCount:'Bilangan Kumpulan',gameTime:'Masa Permainan',targetScore:'Markah Sasaran',questionMode:'Mod Soalan',wrongPenalty:'Denda Jawapan Salah',rightTurn:'Selepas Betul',wrongTurn:'Selepas Salah',showAnswer:'Tunjuk Jawapan Selepas Salah',sound:'Bunyi',questionBank:'Bank Soalan',formatHint:'Format: Arahan | Urutan betul. Guna / untuk pisahkan item. Contoh: Proses AI | Kumpul data / Label imej / Latih model / Uji model.',importTxt:'Import TXT',exportTxt:'Eksport TXT',loadSample:'Muat Sampel',startGame:'Mula Permainan',round:'Pusingan',showSettings:'Tunjuk Tetapan Guru',fullscreen:'Skrin Penuh',nextQuestion:'Soalan Seterusnya',reset:'Tetap Semula',currentQuestion:'Soalan Semasa',currentTeam:'Kumpulan Semasa',readyMsg:'Sedia. Selepas guru klik Mula Permainan, panel tetapan akan disembunyikan.',answerArea:'Ruang Susunan Jawapan',wordBank:'Ruang Kad Perkataan',clickTip:'Klik atau seret kad untuk susun',clearAnswer:'Kosongkan Jawapan',submitAnswer:'Hantar Jawapan',close:'Tutup',playAgain:'Main Lagi',teamRed:'Kumpulan Merah',teamBlue:'Kumpulan Biru',teamGreen:'Kumpulan Hijau',teamPurple:'Kumpulan Ungu',unlimited:'Tiada had',min3:'3 minit',min5:'5 minit',min8:'8 minit',min10:'10 minit',random:'Rawak',order:'Mengikut turutan',yes:'Ya',no:'Tidak',show:'Tunjuk',hide:'Tidak tunjuk',on:'Buka',off:'Tutup',next:'Tukar kumpulan',same:'Kumpulan sama teruskan',needStart:'Sila mulakan permainan dahulu.',bankError:'Bank soalan perlu sekurang-kurangnya 1 soalan, dan setiap soalan perlu sekurang-kurangnya 2 item.',notFull:'Jawapan belum lengkap.',correct:'Betul! Susunan tepat.',wrong:'Salah susunan!',correctAnswer:'Susunan betul: ',gameOver:'Permainan Tamat',winner:'Pemenang',timeUp:'Masa tamat!',targetReached:'Markah sasaran dicapai!',question:'Soalan',score:'Markah',rank:'Kedudukan',loaded:'Bank soalan dimuatkan.',settingsShown:'Tetapan guru dipaparkan.',settingsHidden:'Tetapan guru disembunyikan.',noQuestion:'Tiada soalan tersedia.'}
};
const SAMPLE=`英文句子 | I / like / to / eat / apples
华文句子 | 我 / 今天 / 去 / 学校
马来文句子 | Saya / suka / membaca / buku
AI项目流程 | 收集资料 / 标注图片 / 训练模型 / 测试模型 / 展示成果
历史顺序 | 马六甲王朝建立 / 葡萄牙占领马六甲 / 英国殖民马来亚 / 马来西亚独立
网络安全步骤 | 发现可疑链接 / 不要点击 / 告诉老师或家长 / 删除信息
科学实验步骤 | 提出问题 / 作出假设 / 进行实验 / 记录结果 / 得出结论
作文结构 | 开头 / 发展 / 高潮 / 结尾`;
let state={lang:'zh',started:false,teams:[],teamCount:2,currentTeam:0,questions:[],qIndex:0,round:0,active:null,tokens:[],answer:[],timer:null,timeLeft:300,targetScore:8,settings:{}};
const $=id=>document.getElementById(id); const t=k=>I18N[state.lang][k]||I18N.zh[k]||k;
const els=['langSelect','teamCount','gameMinutes','targetScore','questionMode','wrongPenalty','rightTurn','wrongTurn','showAnswer','soundOn','bankInput'];
function save(){const data={}; els.forEach(id=>data[id]=$(id).value); localStorage.setItem('sentenceOrderGameSettings',JSON.stringify(data));}
function load(){try{const d=JSON.parse(localStorage.getItem('sentenceOrderGameSettings')||'{}'); els.forEach(id=>{if(d[id]!=null)$(id).value=d[id]});}catch(e){} if(!$('bankInput').value.trim())$('bankInput').value=SAMPLE; state.lang=$('langSelect').value||'zh';}
function applyLang(){state.lang=$('langSelect').value; document.documentElement.lang=state.lang==='zh'?'zh-CN':state.lang; document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)}); const gm=$('gameMinutes'); [...gm.options].forEach(o=>{const map={'0':'unlimited','3':'min3','5':'min5','8':'min8','10':'min10'}; o.textContent=t(map[o.value])}); const qm=$('questionMode'); qm.options[0].textContent=t('random'); qm.options[1].textContent=t('order'); $('wrongPenalty').options[0].textContent=t('no'); $('wrongPenalty').options[1].textContent=t('yes'); $('showAnswer').options[0].textContent=t('show'); $('showAnswer').options[1].textContent=t('hide'); $('soundOn').options[0].textContent=t('on'); $('soundOn').options[1].textContent=t('off'); ['rightTurn','wrongTurn'].forEach(id=>{const s=$(id); s.options[0].textContent=t('next'); s.options[1].textContent=t('same')}); renderScoreboard(); updateHeader(); save();}
function parseBank(text){const qs=[]; text.split(/\r?\n/).forEach((line,idx)=>{line=line.trim(); if(!line||line.startsWith('#'))return; let prompt='', order=line; if(line.includes('|')){const parts=line.split('|'); prompt=parts.shift().trim(); order=parts.join('|').trim();}else if(line.includes('=>')){const parts=line.split('=>'); prompt=parts.shift().trim(); order=parts.join('=>').trim();}else if(line.includes('\t')){const parts=line.split('\t'); prompt=parts.shift().trim(); order=parts.join('\t').trim();}else{prompt=t('question')+' '+(idx+1);} let segs=splitSegments(order); if(segs.length>=2)qs.push({prompt,segments:segs,raw:line});}); return qs;}
function splitSegments(s){s=s.trim(); let arr=[]; if(s.includes('/')) arr=s.split('/'); else if(s.includes('→')) arr=s.split('→'); else if(/\s/.test(s)) arr=s.split(/\s+/); else {try{arr=[...s.matchAll(/[\p{Script=Han}]|[A-Za-z0-9]+|[^\s]/gu)].map(m=>m[0]);}catch(e){arr=s.split('')}} return arr.map(x=>x.trim()).filter(Boolean);}
function shuffle(a){const b=a.slice(); for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [b[i],b[j]]=[b[j],b[i]];} return b;}
function makeTeams(n){const keys=['teamRed','teamBlue','teamGreen','teamPurple'], colors=['var(--red)','var(--blue)','var(--green)','var(--purple)'], icons=['🐎','🏎️','🚀','⛵']; return Array.from({length:n},(_,i)=>({name:t(keys[i]),score:0,color:colors[i],icon:icons[i]}));}
function readSettings(){state.teamCount=parseInt($('teamCount').value,10); state.targetScore=Math.max(1,parseInt($('targetScore').value,10)||8); state.settings={minutes:parseInt($('gameMinutes').value,10),mode:$('questionMode').value,wrongPenalty:$('wrongPenalty').value==='yes',rightTurn:$('rightTurn').value,wrongTurn:$('wrongTurn').value,showAnswer:$('showAnswer').value==='yes',sound:$('soundOn').value==='yes'};}
function startGame(){readSettings(); const qs=parseBank($('bankInput').value); if(!qs.length){toast(t('bankError'),'bad'); return;} state.questions=state.settings.mode==='random'?shuffle(qs):qs; state.qIndex=0; state.round=0; state.currentTeam=0; state.teams=makeTeams(state.teamCount); state.started=true; state.timeLeft=state.settings.minutes>0?state.settings.minutes*60:0; document.body.classList.add('playing'); $('rankModal').style.display='none'; renderScoreboard(); updateTimer(); clearInterval(state.timer); if(state.settings.minutes>0){state.timer=setInterval(()=>{state.timeLeft--; updateTimer(); if(state.timeLeft<=0)endGame(t('timeUp'));},1000);} nextQuestion(false); toast(t('settingsHidden'),'warn'); save();}
function updateTimer(){if(state.settings.minutes===0){$('timer').textContent='∞'; return;} const m=Math.floor(state.timeLeft/60), s=state.timeLeft%60; $('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function renderScoreboard(){const board=$('scoreboard'); board.innerHTML=''; const teams=state.teams.length?state.teams:makeTeams(parseInt($('teamCount').value,10)||2); board.style.gridTemplateColumns=`repeat(${Math.min(teams.length,4)},1fr)`; teams.forEach((team,i)=>{const pct=Math.max(0,Math.min(100,(team.score/(state.targetScore||8))*100)); const div=document.createElement('div'); div.className='teamCard '+(state.started&&i===state.currentTeam?'active':''); div.innerHTML=`<div class="teamHead"><span>${team.name}</span><span class="teamScore">${team.score}</span></div><div class="track"><div class="fill" style="width:${pct}%;background:${team.color}"></div></div><div class="teamIcon">${team.icon}</div>`; board.appendChild(div);});}
function updateHeader(){$('gameTitle').textContent=t('title'); $('turnName').textContent=state.teams[state.currentTeam]?.name||'-'; $('roundNo').textContent=state.round||0;}
function nextQuestion(advanceTurn=true){if(!state.started){toast(t('needStart'),'warn'); return;} if(advanceTurn) state.currentTeam=(state.currentTeam+1)%state.teams.length; if(state.settings.mode==='random' && state.qIndex>=state.questions.length){state.questions=shuffle(parseBank($('bankInput').value)); state.qIndex=0;} if(state.settings.mode==='order' && state.qIndex>=state.questions.length) state.qIndex=0; const q=state.questions[state.qIndex++]; if(!q){toast(t('noQuestion'),'bad');return;} state.active=q; state.round++; let shuffled=shuffle(q.segments.map((text,i)=>({id:'tok'+Date.now()+'_'+i,text,placed:null}))); let guard=0; while(shuffled.map(x=>x.text).join('\u0001')===q.segments.join('\u0001') && q.segments.length>2 && guard++<8) shuffled=shuffle(shuffled); state.tokens=shuffled; state.answer=Array(q.segments.length).fill(null); $('questionText').textContent=q.prompt||t('question'); $('answerHint').textContent=''; renderTokens(); renderScoreboard(); updateHeader(); toast('', ''); save();}
function renderTokens(){const bank=$('wordBank'), slots=$('slots'); bank.innerHTML=''; slots.innerHTML=''; state.tokens.filter(tok=>tok.placed==null).forEach(tok=>bank.appendChild(tokenEl(tok))); state.answer.forEach((tok,i)=>{const slot=document.createElement('div'); slot.className='slot'; slot.dataset.n=i+1; slot.dataset.index=i; slot.addEventListener('dragover',e=>{e.preventDefault(); slot.classList.add('over')}); slot.addEventListener('dragleave',()=>slot.classList.remove('over')); slot.addEventListener('drop',e=>{e.preventDefault(); slot.classList.remove('over'); const id=e.dataTransfer.getData('text/plain'); placeToken(id,i);}); if(tok) slot.appendChild(tokenEl(tok,true)); slots.appendChild(slot);}); bank.addEventListener('dragover',e=>e.preventDefault()); bank.addEventListener('drop',e=>{e.preventDefault(); const id=e.dataTransfer.getData('text/plain'); unplaceToken(id)}); $('filledCount').textContent=`${state.answer.filter(Boolean).length}/${state.answer.length}`;}
function tokenEl(tok,inSlot=false){const el=document.createElement('div'); el.className='token'; el.draggable=true; el.textContent=tok.text; el.dataset.id=tok.id; el.addEventListener('dragstart',e=>{el.classList.add('dragging'); e.dataTransfer.setData('text/plain',tok.id)}); el.addEventListener('dragend',()=>el.classList.remove('dragging')); el.addEventListener('click',()=>{if(inSlot)unplaceToken(tok.id); else placeToken(tok.id,firstEmpty());}); return el;}
function firstEmpty(){return state.answer.findIndex(x=>!x)}
function findToken(id){return state.tokens.find(x=>x.id===id)}
function placeToken(id,index){if(index<0)return; const tok=findToken(id); if(!tok)return; if(tok.placed!=null) state.answer[tok.placed]=null; if(state.answer[index]) state.answer[index].placed=null; tok.placed=index; state.answer[index]=tok; renderTokens();}
function unplaceToken(id){const tok=findToken(id); if(!tok)return; if(tok.placed!=null){state.answer[tok.placed]=null; tok.placed=null; renderTokens();}}
function clearAnswer(){state.tokens.forEach(t=>t.placed=null); state.answer=Array(state.active?.segments.length||0).fill(null); renderTokens();}
function checkAnswer(){if(!state.started||!state.active){toast(t('needStart'),'warn'); return;} if(state.answer.some(x=>!x)){toast(t('notFull'),'warn'); return;} const user=state.answer.map(x=>x.text); const ok=user.length===state.active.segments.length && user.every((v,i)=>v===state.active.segments[i]); if(ok) handleCorrect(); else handleWrong();}
function handleCorrect(){const team=state.teams[state.currentTeam]; team.score++; sound('good'); toast(t('correct'),'good'); confetti(); renderScoreboard(); if(team.score>=state.targetScore){endGame(t('targetReached')); return;} setTimeout(()=>{if(state.settings.rightTurn==='next') nextQuestion(true); else nextQuestion(false);},900);}
function handleWrong(){const team=state.teams[state.currentTeam]; if(state.settings.wrongPenalty) team.score--; sound('bad'); renderScoreboard(); const ans=state.active.segments.join(' / '); toast(t('wrong')+(state.settings.showAnswer?' '+t('correctAnswer')+ans:''),'bad'); $('answerHint').textContent=state.settings.showAnswer?t('correctAnswer')+ans:''; setTimeout(()=>{if(state.settings.wrongTurn==='next') nextQuestion(true); else nextQuestion(false);}, state.settings.showAnswer?1800:900);}
function toast(msg,type){const m=$('message'); m.textContent=msg||''; m.className='message '+(type||'');}
function sound(kind){if(!state.settings.sound)return; try{const ctx=new (window.AudioContext||window.webkitAudioContext)(); const o=ctx.createOscillator(), g=ctx.createGain(); o.connect(g); g.connect(ctx.destination); o.frequency.value=kind==='good'?740:170; o.type=kind==='good'?'triangle':'sawtooth'; g.gain.setValueAtTime(.0001,ctx.currentTime); g.gain.exponentialRampToValueAtTime(.12,ctx.currentTime+.02); g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.22); o.start(); o.stop(ctx.currentTime+.24);}catch(e){}}
function endGame(reason){if(!state.started)return; clearInterval(state.timer); state.started=false; document.body.classList.remove('playing'); const ranked=state.teams.slice().sort((a,b)=>b.score-a.score); $('endTitle').textContent=`${t('gameOver')} · ${reason}`; const list=$('rankList'); list.innerHTML=''; ranked.forEach((team,i)=>{const item=document.createElement('div'); item.className='rankItem'; item.innerHTML=`<span>${i+1}. ${team.name} ${i===0?'🏆':''}</span><span>${team.score} ${t('score')}</span>`; list.appendChild(item);}); $('rankModal').style.display='flex'; renderScoreboard(); updateHeader();}
function resetGame(){clearInterval(state.timer); state.started=false; document.body.classList.remove('playing'); state.teams=makeTeams(parseInt($('teamCount').value,10)||2); state.currentTeam=0; state.round=0; state.active=null; state.tokens=[]; state.answer=[]; $('rankModal').style.display='none'; $('questionText').textContent=t('readyMsg'); $('answerHint').textContent=''; $('wordBank').innerHTML=''; $('slots').innerHTML=''; $('filledCount').textContent='0/0'; toast(t('readyMsg'),''); readSettings(); state.timeLeft=state.settings.minutes*60; updateTimer(); renderScoreboard(); updateHeader();}
function confetti(){const c=$('confetti'); c.innerHTML=''; const colors=['#60a5fa','#22c55e','#f59e0b','#ef4444','#a855f7','#f472b6']; for(let i=0;i<38;i++){const x=document.createElement('i'); x.style.left=Math.random()*100+'vw'; x.style.background=colors[i%colors.length]; x.style.animationDelay=(Math.random()*.25)+'s'; x.style.transform=`rotate(${Math.random()*360}deg)`; c.appendChild(x);} setTimeout(()=>c.innerHTML='',2100);}
function exportTxt(){const blob=new Blob([$('bankInput').value],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='sentence_order_questions.txt'; a.click(); URL.revokeObjectURL(a.href);}
function importTxt(file){const r=new FileReader(); r.onload=()=>{$('bankInput').value=r.result; toast(t('loaded'),'good'); save();}; r.readAsText(file,'utf-8');}
function fullscreen(){const el=document.documentElement; if(!document.fullscreenElement) el.requestFullscreen?.(); else document.exitFullscreen?.();}
$('langSelect').addEventListener('change',applyLang); ['teamCount','gameMinutes','targetScore','questionMode','wrongPenalty','rightTurn','wrongTurn','showAnswer','soundOn','bankInput'].forEach(id=>$(id).addEventListener('change',save)); $('bankInput').addEventListener('input',save);
$('startBtn').addEventListener('click',startGame); $('showSettingsBtn').addEventListener('click',()=>{document.body.classList.toggle('playing'); toast(document.body.classList.contains('playing')?t('settingsHidden'):t('settingsShown'),'warn')}); $('fullscreenBtn').addEventListener('click',fullscreen); $('nextBtn').addEventListener('click',()=>nextQuestion(true)); $('resetBtn').addEventListener('click',resetGame); $('clearBtn').addEventListener('click',clearAnswer); $('checkBtn').addEventListener('click',checkAnswer); $('sampleBtn').addEventListener('click',()=>{$('bankInput').value=SAMPLE; save(); toast(t('loaded'),'good')}); $('exportBtn').addEventListener('click',exportTxt); $('importBtn').addEventListener('click',()=>$('fileInput').click()); $('fileInput').addEventListener('change',e=>{if(e.target.files[0]) importTxt(e.target.files[0])}); $('closeRankBtn').addEventListener('click',()=>$('rankModal').style.display='none'); $('playAgainBtn').addEventListener('click',()=>{ $('rankModal').style.display='none'; startGame();});
load(); applyLang(); resetGame();
