
const $=s=>document.querySelector(s);let lang='zh',qs=[],sectors=[],pending=null,crystals=0,fuel=12,oxygen=5,score=0,target=6,logs=[],endAt=0,timerId=null;
const L={zh:{title:'太空水晶任務',sub:'探索星區、答題收集水晶，同時管理燃料與氧氣。',setup:'設定題庫',full:'全屏',reset:'重開',status:'任務狀態',ruleTitle:'玩法',rule:'點選星區並回答題目。答對可收集水晶或能源；答錯會消耗氧氣。每次移動都會消耗燃料。收集足夠水晶即可完成任務。',round:'太空船待命',hint:'選擇一個星區探索。',target:n=>`目標：${n} 水晶`,explore:n=>`探索：${n}/12`,warning:'小心黑洞',spaceHint:'水晶星區可得水晶，能源站可補燃料，黑洞會消耗氧氣。',scan:'重新掃描星圖',log:'任務記錄',setupTitle:'太空水晶任務｜老師設定',setupHelp:'題庫格式：題目|選項A|選項B|選項C|選項D|正確答案編號。每行一題。',sample:'載入示範',start:'開始任務',correct:'答對，星區探索成功',wrong:'答錯，氧氣下降',win:'水晶收集完成，任務成功！',lose:'燃料或氧氣不足，任務失敗。',again:'再玩一次'},en:{title:'Space Crystal Mission',sub:'Explore sectors, answer questions, collect crystals, and manage fuel and oxygen.',setup:'Questions',full:'Fullscreen',reset:'Restart',status:'Mission status',ruleTitle:'How to play',rule:'Choose a space sector and answer a question. Correct answers collect crystals or energy; wrong answers consume oxygen. Each move consumes fuel. Collect enough crystals to complete the mission.',round:'Ship ready',hint:'Choose a sector to explore.',target:n=>`Target: ${n} crystals`,explore:n=>`Explored: ${n}/12`,warning:'Beware black holes',spaceHint:'Crystal sectors give crystals, stations refill fuel, black holes cost oxygen.',scan:'Rescan map',log:'Mission log',setupTitle:'Space Crystal Mission | Settings',setupHelp:'Format: question|A|B|C|D|correct number. One question per line.',sample:'Load sample',start:'Start mission',correct:'Correct! Sector explored',wrong:'Wrong! Oxygen decreased',win:'Crystals collected. Mission success!',lose:'Fuel or oxygen ran out. Mission failed.',again:'Play again'},ms:{title:'Misi Kristal Angkasa',sub:'Teroka sektor, jawab soalan, kumpul kristal, dan urus bahan api serta oksigen.',setup:'Soalan',full:'Skrin penuh',reset:'Mula semula',status:'Status misi',ruleTitle:'Cara bermain',rule:'Pilih sektor angkasa dan jawab soalan. Betul mengumpul kristal atau tenaga; salah mengurangkan oksigen. Setiap pergerakan menggunakan bahan api. Kumpul kristal mencukupi untuk berjaya.',round:'Kapal sedia',hint:'Pilih sektor untuk diteroka.',target:n=>`Sasaran: ${n} kristal`,explore:n=>`Diteroka: ${n}/12`,warning:'Awas lubang hitam',spaceHint:'Sektor kristal memberi kristal, stesen menambah bahan api, lubang hitam mengurangkan oksigen.',scan:'Imbas semula peta',log:'Rekod misi',setupTitle:'Misi Kristal Angkasa | Tetapan',setupHelp:'Format: soalan|A|B|C|D|nombor jawapan betul. Satu soalan setiap baris.',sample:'Muat contoh',start:'Mula misi',correct:'Betul! Sektor diteroka',wrong:'Salah! Oksigen berkurang',win:'Kristal cukup. Misi berjaya!',lose:'Bahan api atau oksigen habis. Misi gagal.',again:'Main lagi'}};const t=(k,...a)=>{const v=L[lang][k];return typeof v==='function'?v(...a):v||k};
function sample(){$('#questionText').value='AI 可以幫助我們？|學習|亂發訊息|偷資料|不思考|1\n安全密碼應該包含？|生日|123456|大小寫與符號|名字|3\n看到陌生人索取資料應該？|直接給|拒絕並告訴大人|公開資料|不理會規則|2\n哪一個是負責任使用 AI？|抄襲|標明協助|傷害別人|製造謠言|2';}
function parse(){return $('#questionText').value.split('\n').map(r=>r.trim()).filter(Boolean).map(r=>{let p=r.split('|').map(x=>x.trim());return{q:p[0],opts:p.slice(1,5),ans:Number(p[5]||1)-1}}).filter(x=>x.q&&x.opts.length>=4)}
function makeSectors(){let types=['crystal','crystal','crystal','crystal','energy','energy','score','score','asteroid','asteroid','blackhole','crystal'];sectors=types.sort(()=>Math.random()-.5).map((type,i)=>({type,open:false,i}));}
function start(){qs=parse();if(!qs.length){sample();qs=parse()}target=Number($('#targetInput').value||6);fuel=Number($('#fuelInput').value||12);oxygen=5;crystals=0;score=0;logs=[];makeSectors();$('#setup').classList.add('hidden');endAt=Date.now()+Number($('#timeLimit').value||360)*1000;clearInterval(timerId);timerId=setInterval(tick,200);render()}
function tick(){let s=Math.max(0,Math.ceil((endAt-Date.now())/1000));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(s<=0)finish(false)}
function render(){$('#crystals').textContent=crystals;$('#fuel').textContent=fuel;$('#oxygen').textContent=oxygen;$('#score').textContent=score;$('#targetText').textContent=t('target',target);$('#exploreText').textContent=t('explore',sectors.filter(x=>x.open).length);$('#warningText').textContent=t('warning');$('#sectors').innerHTML='';sectors.forEach(sec=>{let d=document.createElement('div');d.className='sector '+(sec.open?(sec.type==='blackhole'?'danger':'done'):'');let icon=sec.open?({crystal:'💎',energy:'⛽',score:'⭐',asteroid:'🪨',blackhole:'🕳️'}[sec.type]):'🌌';d.innerHTML='<span>'+icon+'</span><small>'+(sec.open?sec.type:'Sector '+(sec.i+1))+'</small>';d.onclick=()=>{if(!sec.open)ask(sec)};$('#sectors').appendChild(d)});$('#logs').innerHTML=logs.map(x=>'<div class="log">'+x+'</div>').join('')}
function ask(sec){if(fuel<=0||oxygen<=0){finish(false);return}fuel--;pending=sec;let q=qs[Math.floor(Math.random()*qs.length)];pending.q=q;$('#modalTitle').textContent='🚀 Sector '+(sec.i+1);$('#modalMeta').textContent='Fuel -1';$('#modalQ').textContent=q.q;$('#qOptions').innerHTML='';q.opts.forEach((o,i)=>{let b=document.createElement('button');b.className='opt';b.textContent=String.fromCharCode(65+i)+'. '+o;b.onclick=()=>answer(i===q.ans);$('#qOptions').appendChild(b)});$('#quizModal').classList.remove('hidden');render()}
function answer(ok){$('#quizModal').classList.add('hidden');let sec=pending;sec.open=true;if(ok){if(sec.type==='crystal')crystals++; if(sec.type==='energy')fuel+=3; if(sec.type==='score')score+=20; if(sec.type==='asteroid')score+=5; if(sec.type==='blackhole')oxygen--; logs.unshift('✅ '+t('correct')+' '+({crystal:'💎',energy:'⛽',score:'⭐',asteroid:'🪨',blackhole:'🕳️'}[sec.type]));}else{oxygen--;logs.unshift('❌ '+t('wrong'))}logs=logs.slice(0,8);if(crystals>=target)finish(true);else if(fuel<=0||oxygen<=0)finish(false);render()}
function finish(win){clearInterval(timerId);$('#win').classList.remove('hidden');$('#winTitle').textContent=win?t('win'):t('lose');$('#winDesc').textContent='💎 '+crystals+' ｜ ⛽ '+fuel+' ｜ 🫧 '+oxygen+' ｜ ⭐ '+score}
function apply(){document.title=t('title');$('#title').textContent=t('title');$('#subtitle').textContent=t('sub');$('#setupBtn').textContent=t('setup');$('#fullBtn').textContent=t('full');$('#resetBtn').textContent=t('reset');$('#statusTitle').textContent=t('status');$('#ruleTitle').textContent=t('ruleTitle');$('#ruleText').textContent=t('rule');$('#roundText').textContent=t('round');$('#hintText').textContent=t('hint');$('#spaceHint').textContent=t('spaceHint');$('#scanBtn').textContent=t('scan');$('#logTitle').textContent=t('log');$('#setupTitle').textContent=t('setupTitle');$('#setupHelp').textContent=t('setupHelp');$('#sampleBtn').textContent=t('sample');$('#startBtn').textContent=t('start');$('#againBtn').textContent=t('again');render()}
$('#lang').onchange=e=>{lang=e.target.value;apply()};$('#setupBtn').onclick=()=>$('#setup').classList.remove('hidden');$('#fullBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('#resetBtn').onclick=()=>location.reload();$('#sampleBtn').onclick=sample;$('#startBtn').onclick=start;$('#scanBtn').onclick=()=>{makeSectors();render()};sample();makeSectors();apply();
