
const I18N={
 zh:{title:"时间线排序挑战",subtitle:"老师输入事件或步骤，学生把卡片拖成正确时间线。",setup:"设置题库",fullscreen:"全屏",restart:"重开",setupTitle:"时间线排序挑战｜老师设置",setupHelp:"适合历史、科学流程、作文结构、项目步骤。可直接按行输入，系统会以输入顺序作为正确顺序。",scoreTitle:"成绩",score:"分数",attempt:"检查次数",ruleTitle:"玩法说明",ruleText:"把卡片拖到正确顺序，然后按检查。全部正确即完成挑战。",round:"排序项目",hint:"拖动卡片调整顺序。",check:"检查答案",shuffle:"重新打乱",logTitle:"记录",sample:"载入示范",start:"开始游戏",again:"再玩一次",finish:"完成！",finalScore:"最终得分",placeholder:"每行一个事件/步骤，正确顺序就是输入顺序。\\n例：\\n种子发芽\\n长出叶子\\n开花\\n结果",wrong:"还有顺序不正确。",correct:"全部正确！"},
 en:{title:"Timeline Sorting Challenge",subtitle:"Teachers enter events or steps. Students drag cards into the correct timeline.",setup:"Question settings",fullscreen:"Fullscreen",restart:"Restart",setupTitle:"Timeline Sorting Challenge | Teacher Settings",setupHelp:"Suitable for history, science processes, writing structure and project steps. Enter one item per line; row order is the correct order.",scoreTitle:"Score",score:"Score",attempt:"Checks",ruleTitle:"How to play",ruleText:"Drag cards into the correct order, then check. Complete the challenge when all are correct.",round:"Items",hint:"Drag cards to reorder.",check:"Check answer",shuffle:"Shuffle again",logTitle:"Log",sample:"Load sample",start:"Start game",again:"Play again",finish:"Finished!",finalScore:"Final score",placeholder:"One event/step per line. Row order is correct order.\\nExample:\\nSeed germinates\\nLeaves grow\\nFlowers bloom\\nFruit forms",wrong:"Some cards are still in the wrong order.",correct:"All correct!"},
 ms:{title:"Cabaran Susun Garis Masa",subtitle:"Guru memasukkan peristiwa atau langkah. Murid menyeret kad ke garis masa yang betul.",setup:"Tetapan soalan",fullscreen:"Skrin penuh",restart:"Mula semula",setupTitle:"Cabaran Susun Garis Masa | Tetapan Guru",setupHelp:"Sesuai untuk sejarah, proses sains, struktur karangan dan langkah projek. Masukkan satu item setiap baris; urutan baris ialah jawapan betul.",scoreTitle:"Markah",score:"Markah",attempt:"Semakan",ruleTitle:"Cara bermain",ruleText:"Seret kad ke urutan betul, kemudian semak. Cabaran selesai apabila semuanya betul.",round:"Item",hint:"Seret kad untuk susun semula.",check:"Semak jawapan",shuffle:"Kocok semula",logTitle:"Rekod",sample:"Muat contoh",start:"Mula permainan",again:"Main lagi",finish:"Selesai!",finalScore:"Markah akhir",placeholder:"Satu peristiwa/langkah setiap baris. Urutan baris ialah jawapan betul.\\nContoh:\\nBenih bercambah\\nDaun tumbuh\\nBunga mekar\\nBuah terbentuk",wrong:"Masih ada kad yang salah urutan.",correct:"Semua betul!"}
};
let lang=new URLSearchParams(location.search).get("lang")||localStorage.getItem("timeline_lang")||"zh";let items=[],attempts=0,score=0,timerId=null,endAt=0,logs=[];
const $=s=>document.querySelector(s);function T(k){return(I18N[lang]||I18N.zh)[k]||k}
function applyLang(){document.documentElement.lang=lang==="zh"?"zh-Hans":lang;document.title=T("title");["title","subtitle","setupTitle","setupHelp","scoreTitle","ruleTitle","ruleText","logTitle"].forEach(id=>$("#"+id).textContent=T(id));$("#setupBtn").textContent=T("setup");$("#fullBtn").textContent=T("fullscreen");$("#resetBtn").textContent=T("restart");$("#scoreLabel").textContent=T("score");$("#attemptLabel").textContent=T("attempt");$("#hintText").textContent=T("hint");$("#checkBtn").textContent=T("check");$("#shuffleBtn").textContent=T("shuffle");$("#sampleBtn").textContent=T("sample");$("#startBtn").textContent=T("start");$("#againBtn").textContent=T("again");$("#itemText").placeholder=T("placeholder");$("#lang").value=lang;$("#setupLang").value=lang;updateStats();}
function parseItems(){const rows=$("#itemText").value.split("\n").map(x=>x.trim()).filter(Boolean);return rows.map((row,i)=>{const p=row.split("|").map(x=>x.trim());if($("#mode").value==="number"&&p.length>=2)return{order:Number(p[0])||i+1,text:p.slice(1).join(" | ")};return{order:i+1,text:row};}).sort((a,b)=>a.order-b.order)}
function sample(){const s=lang==="en"?"Seed germinates\nLeaves grow\nFlowers bloom\nFruit forms":lang==="ms"?"Benih bercambah\nDaun tumbuh\nBunga mekar\nBuah terbentuk":"种子发芽\n长出叶子\n开花\n结果";$("#itemText").value=s;}
function start(){items=parseItems();if(items.length<2){sample();items=parseItems();}items=[...items].sort(()=>Math.random()-.5);attempts=0;score=0;logs=[];$("#setup").classList.add("hidden");render();endAt=Date.now()+Number($("#timeLimit").value||180)*1000;timerId=setInterval(tick,200);updateStats();}
function tick(){const left=Math.max(0,endAt-Date.now());const s=Math.ceil(left/1000);$("#timer").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(left<=0)check(true)}
function render(){const tl=$("#timeline");tl.innerHTML=items.map((it,i)=>`<div class="card" draggable="true" data-order="${it.order}" data-pos="${i+1}"><b>${it.text}</b><span>#${it.order}</span></div>`).join("");bindDrag();$("#roundText").textContent=`${T("round")}：${items.length}`;renderLogs();}
function bindDrag(){let drag=null;document.querySelectorAll(".card").forEach(card=>{card.addEventListener("dragstart",()=>{drag=card;card.classList.add("dragging")});card.addEventListener("dragend",()=>{card.classList.remove("dragging");drag=null;syncItems()});card.addEventListener("dragover",e=>{e.preventDefault();const after=getAfterElement($("#timeline"),e.clientY);if(!drag)return;if(after==null)$("#timeline").appendChild(drag);else $("#timeline").insertBefore(drag,after);renumber();});});}
function getAfterElement(container,y){const els=[...container.querySelectorAll(".card:not(.dragging)")];return els.reduce((closest,child)=>{const box=child.getBoundingClientRect();const offset=y-box.top-box.height/2;if(offset<0&&offset>closest.offset)return{offset,element:child};return closest},{offset:Number.NEGATIVE_INFINITY}).element}
function renumber(){document.querySelectorAll(".card").forEach((c,i)=>c.dataset.pos=i+1)}
function syncItems(){items=[...document.querySelectorAll(".card")].map(c=>({order:Number(c.dataset.order),text:c.querySelector("b").textContent}))}
function check(timeout=false){attempts++;syncItems();let ok=true;document.querySelectorAll(".card").forEach((c,i)=>{const correct=Number(c.dataset.order)===i+1;c.classList.toggle("correct",correct);c.classList.toggle("wrong",!correct);if(!correct)ok=false;});if(ok){score=Math.max(10,100-(attempts-1)*10);addLog("✅ "+T("correct"));finish();}else{score=Math.max(0,score-5);addLog("❌ "+T("wrong"));if(timeout)finish();}updateStats();}
function shuffleAgain(){items=[...items].sort(()=>Math.random()-.5);render();}
function updateStats(){$("#score").textContent=score;$("#attempts").textContent=attempts}
function addLog(x){logs.unshift(x);logs=logs.slice(0,8);renderLogs()}
function renderLogs(){$("#logs").innerHTML=logs.map(x=>`<div class="log">${x}</div>`).join("")}
function finish(){clearInterval(timerId);$("#winTitle").textContent=T("finish");$("#winDesc").textContent=`${T("finalScore")}：${score}｜${T("attempt")}：${attempts}`;$("#win").classList.remove("hidden")}
$("#lang").onchange=e=>{lang=e.target.value;localStorage.setItem("timeline_lang",lang);applyLang()};$("#setupLang").onchange=e=>{lang=e.target.value;localStorage.setItem("timeline_lang",lang);applyLang()};$("#sampleBtn").onclick=sample;$("#startBtn").onclick=start;$("#checkBtn").onclick=()=>check(false);$("#shuffleBtn").onclick=shuffleAgain;$("#setupBtn").onclick=()=>$("#setup").classList.remove("hidden");$("#resetBtn").onclick=()=>location.reload();$("#fullBtn").onclick=()=>document.documentElement.requestFullscreen?.();applyLang();sample();
