
(function(){
  const I18N={
    zh:{appTitle:'打地鼠问答',appSub:'看到题目后，快速打中正确答案地鼠，适合课堂复习与词汇问答',showSettings:'显示老师设定',fullscreen:'全屏',reset:'重置',teacherSettings:'老师设定',uiLang:'介面语言',teamCount:'组数',gameTime:'游戏时间',noLimit:'不限时',roundTime:'每题倒数',targetScore:'目标分',noTarget:'不设目标',correctPoint:'答对得分',wrongPenalty:'答错扣分',noDeduct:'不扣分',moleSpeed:'地鼠移动速度',slow:'慢',normal:'普通',fast:'快',answerCount:'答案数量',questionMode:'题目顺序',random:'随机',order:'顺序',sound:'音效',on:'开启',off:'关闭',afterCorrect:'答对后',afterWrong:'答错 / 超时后',switchTeam:'换下一组',sameTeam:'本组继续',questionBank:'题库',bankHint:'格式：题目,正确答案,错误选项1,错误选项2,错误选项3。若只填“题目,答案”，系统会从其他答案中抽干扰选项。',importTxt:'汇入 TXT',exportTxt:'导出 TXT',startGame:'开始游戏',startHint:'开始后老师设定区会隐藏，只保留游戏介面，适合投影使用。',turn:'轮到',roundInfo:'看题目，打中正确答案地鼠。',goal:'目标',goalSmall:'答对得分，答错可扣分，最先达到目标分获胜。',question:'题目',readyText:'按“开始游戏”后开始打地鼠。',readyHint:'老师可先设定组数、时间、题库和目标分。',skipQuestion:'跳过 / 下一题',pause:'暂停',resume:'继续',feedbackReady:'游戏尚未开始。',rulesTitle:'玩法说明',rulesSub:'适合投影到大屏幕，全班分组轮流上来点击正确答案。',rule1:'老师输入题库，每行一个问题。',rule2:'轮到的小组看题目，打中正确答案地鼠。',rule3:'答对加分，答错或超时按设定扣分或换组。',rule4:'达到目标分或时间结束后显示排名。',logTitle:'课堂记录',gameOver:'游戏结束',close:'关闭',winner:'获胜队伍',score:'分',round:'第 {n} 题',correct:'答对！',wrong:'答错！',timeout:'时间到！',correctAnswer:'正确答案',paused:'已暂停',emptyBank:'题库为空，请先输入题库。',badBank:'题库格式不足，请至少输入：题目,正确答案',red:'红队',blue:'蓝队',green:'绿队',purple:'紫队',startMsg:'游戏开始！请打中正确答案地鼠。',skipMsg:'老师跳过本题。',ranking:'最终排名',hitHint:'点击正在冒出来的正确答案地鼠。'},
    en:{appTitle:'Whack-a-Mole Quiz',appSub:'Read the question and hit the mole with the correct answer. Great for classroom review.',showSettings:'Show Teacher Settings',fullscreen:'Fullscreen',reset:'Reset',teacherSettings:'Teacher Settings',uiLang:'UI Language',teamCount:'Teams',gameTime:'Game Time',noLimit:'No limit',roundTime:'Question Timer',targetScore:'Target Score',noTarget:'No target',correctPoint:'Points for Correct',wrongPenalty:'Penalty for Wrong',noDeduct:'No penalty',moleSpeed:'Mole Speed',slow:'Slow',normal:'Normal',fast:'Fast',answerCount:'Number of Answers',questionMode:'Question Order',random:'Random',order:'In order',sound:'Sound',on:'On',off:'Off',afterCorrect:'After Correct',afterWrong:'After Wrong / Timeout',switchTeam:'Next team',sameTeam:'Same team continues',questionBank:'Question Bank',bankHint:'Format: Question,Correct Answer,Wrong Option 1,Wrong Option 2,Wrong Option 3. If only Question,Answer is provided, distractors are drawn from other answers.',importTxt:'Import TXT',exportTxt:'Export TXT',startGame:'Start Game',startHint:'After starting, teacher settings will be hidden for classroom projection.',turn:'Turn',roundInfo:'Read the question and hit the correct answer mole.',goal:'Goal',goalSmall:'Score for correct answers. Wrong answers may deduct points. First to target wins.',question:'Question',readyText:'Press “Start Game” to begin.',readyHint:'Set teams, time, question bank, and target score first.',skipQuestion:'Skip / Next Question',pause:'Pause',resume:'Resume',feedbackReady:'Game has not started.',rulesTitle:'How to Play',rulesSub:'Project to a screen. Teams take turns clicking the correct answer.',rule1:'Teacher enters one question per line.',rule2:'The current team reads the question and hits the correct mole.',rule3:'Correct answers score points; wrong answers or timeout follow your settings.',rule4:'Ranking appears when the target is reached or time is over.',logTitle:'Class Log',gameOver:'Game Over',close:'Close',winner:'Winner',score:'pts',round:'Question {n}',correct:'Correct!',wrong:'Wrong!',timeout:'Time is up!',correctAnswer:'Correct answer',paused:'Paused',emptyBank:'The question bank is empty.',badBank:'Invalid format. Use at least: Question,Correct Answer',red:'Red Team',blue:'Blue Team',green:'Green Team',purple:'Purple Team',startMsg:'Game started! Hit the correct answer mole.',skipMsg:'Teacher skipped this question.',ranking:'Final Ranking',hitHint:'Click the mole showing the correct answer.'},
    ms:{appTitle:'Kuiz Pukul Tikus Tanah',appSub:'Baca soalan dan pukul tikus tanah dengan jawapan yang betul. Sesuai untuk ulang kaji kelas.',showSettings:'Tunjuk Tetapan Guru',fullscreen:'Skrin Penuh',reset:'Tetap Semula',teacherSettings:'Tetapan Guru',uiLang:'Bahasa Paparan',teamCount:'Bilangan Kumpulan',gameTime:'Masa Permainan',noLimit:'Tiada had',roundTime:'Masa Soalan',targetScore:'Sasaran Markah',noTarget:'Tiada sasaran',correctPoint:'Markah Jawapan Betul',wrongPenalty:'Potong Markah Salah',noDeduct:'Tidak potong',moleSpeed:'Kelajuan Tikus',slow:'Perlahan',normal:'Biasa',fast:'Laju',answerCount:'Bilangan Jawapan',questionMode:'Susunan Soalan',random:'Rawak',order:'Ikut turutan',sound:'Bunyi',on:'Buka',off:'Tutup',afterCorrect:'Selepas Betul',afterWrong:'Selepas Salah / Tamat Masa',switchTeam:'Kumpulan seterusnya',sameTeam:'Kumpulan ini teruskan',questionBank:'Bank Soalan',bankHint:'Format: Soalan,Jawapan Betul,Pilihan Salah 1,Pilihan Salah 2,Pilihan Salah 3. Jika hanya Soalan,Jawapan, sistem akan ambil pilihan gangguan daripada jawapan lain.',importTxt:'Import TXT',exportTxt:'Eksport TXT',startGame:'Mula Permainan',startHint:'Selepas mula, tetapan guru akan disembunyikan untuk paparan projektor.',turn:'Giliran',roundInfo:'Baca soalan dan pukul jawapan yang betul.',goal:'Sasaran',goalSmall:'Jawapan betul dapat markah. Salah boleh dipotong. Kumpulan pertama capai sasaran menang.',question:'Soalan',readyText:'Tekan “Mula Permainan” untuk bermula.',readyHint:'Tetapkan kumpulan, masa, bank soalan dan sasaran markah dahulu.',skipQuestion:'Langkau / Soalan Seterusnya',pause:'Jeda',resume:'Sambung',feedbackReady:'Permainan belum bermula.',rulesTitle:'Cara Bermain',rulesSub:'Paparkan pada skrin. Kumpulan bergilir-gilir klik jawapan betul.',rule1:'Guru masukkan satu soalan setiap baris.',rule2:'Kumpulan giliran membaca soalan dan pukul tikus tanah yang betul.',rule3:'Jawapan betul dapat markah; salah atau tamat masa ikut tetapan guru.',rule4:'Kedudukan dipaparkan apabila sasaran dicapai atau masa tamat.',logTitle:'Rekod Kelas',gameOver:'Permainan Tamat',close:'Tutup',winner:'Pemenang',score:'markah',round:'Soalan {n}',correct:'Betul!',wrong:'Salah!',timeout:'Masa tamat!',correctAnswer:'Jawapan betul',paused:'Dijeda',emptyBank:'Bank soalan kosong.',badBank:'Format tidak cukup. Guna sekurang-kurangnya: Soalan,Jawapan Betul',red:'Kumpulan Merah',blue:'Kumpulan Biru',green:'Kumpulan Hijau',purple:'Kumpulan Ungu',startMsg:'Permainan bermula! Pukul jawapan yang betul.',skipMsg:'Guru melangkau soalan ini.',ranking:'Kedudukan Akhir',hitHint:'Klik tikus tanah yang memaparkan jawapan betul.'}
  };
  const $=id=>document.getElementById(id);
  const els={layout:$('layout'),lang:$('langSelect'),teamCount:$('teamCount'),gameTime:$('gameTime'),roundTime:$('roundTime'),targetScore:$('targetScore'),correctPoint:$('correctPoint'),wrongPenalty:$('wrongPenalty'),moleSpeed:$('moleSpeed'),answerCount:$('answerCount'),questionMode:$('questionMode'),sound:$('sound'),afterCorrect:$('afterCorrect'),afterWrong:$('afterWrong'),questionBank:$('questionBank'),teams:$('teams'),gameTimer:$('gameTimer'),roundTimer:$('roundTimer'),roundFill:$('roundFill'),turnName:$('turnName'),goalText:$('goalText'),questionText:$('questionText'),questionHint:$('questionHint'),questionNo:$('questionNo'),holes:$('holes'),feedback:$('feedback'),logList:$('logList'),modalBackdrop:$('modalBackdrop'),modalBody:$('modalBody'),pauseBtn:$('pauseBtn')};
  const sampleBank=`马来西亚首都是哪里？,吉隆坡,新山,槟城,马六甲,怡保
AI 的英文全名是什么？,Artificial Intelligence,Automatic Internet,Advanced Image,Artificial Internet,Auto Intelligence
password 的中文意思是什么？,密码,账号,网络,电脑,登入
水的化学式是什么？,H2O,CO2,O2,NaCl,H2
太阳从哪里升起？,东方,西方,南方,北方,中间
早安 的马来文是什么？,selamat pagi,terima kasih,selamat malam,apa khabar,sama-sama
CPU 的中文是什么？,中央处理器,显示器,键盘,滑鼠,硬盘
植物制造养分的过程叫什么？,光合作用,蒸发作用,呼吸作用,消化作用,摩擦作用
AI 可以随便用同学照片做搞笑图吗？,不可以,可以,只要好笑就可以,老师没看到就可以,发到群组就可以
在网上看到不明链接应该怎么做？,不要随便点击,马上点击,转发给朋友,输入密码试试看,下载文件`;
  let lang='zh',teams=[],currentTeam=0,questions=[],qIndex=0,roundNo=0,currentQuestion=null,currentOptions=[],running=false,paused=false,answered=false,gameLeft=300,roundLeft=10,gameTimerInt=null,roundTimerInt=null,moleInt=null,logs=[];
  const teamTemplates=[{key:'red',color:'var(--red)',icon:'🔴'},{key:'blue',color:'var(--blue)',icon:'🔵'},{key:'green',color:'var(--green)',icon:'🟢'},{key:'purple',color:'var(--purple)',icon:'🟣'}];
  function t(k,vars={}){let s=(I18N[lang]&&I18N[lang][k])||I18N.zh[k]||k;return s.replace(/\{(\w+)\}/g,(_,v)=>vars[v]??'');}
  function applyI18n(){lang=els.lang.value;document.documentElement.lang=lang==='zh'?'zh-CN':lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(I18N[lang][k]) el.textContent=I18N[lang][k];});updateDynamicTexts();renderTeams();}
  function updateDynamicTexts(){els.goalText.textContent=+els.targetScore.value?els.targetScore.value:t('noTarget');if(!running){els.questionText.textContent=t('readyText');els.questionHint.textContent=t('readyHint');els.feedback.textContent=t('feedbackReady');}if(teams[currentTeam]) els.turnName.textContent=teams[currentTeam].name;}
  function parseCSV(line){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if((ch===','||ch==='，')&&!q){out.push(cur.trim());cur='';}else cur+=ch;}out.push(cur.trim());return out.filter(x=>x.length>0);}
  function parseBank(){const lines=els.questionBank.value.split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!x.startsWith('#'));const qs=[];for(const line of lines){const parts=parseCSV(line);if(parts.length>=2){qs.push({q:parts[0],correct:parts[1],distractors:parts.slice(2)});}}return qs;}
  function shuffle(a){const arr=[...a];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
  function norm(s){return String(s??'').trim().toLowerCase().replace(/\s+/g,' ');}
  function fmt(sec){sec=Math.max(0,Math.floor(sec));const m=String(Math.floor(sec/60)).padStart(2,'0');const s=String(sec%60).padStart(2,'0');return `${m}:${s}`;}
  function setupTeams(){const n=+els.teamCount.value;teams=teamTemplates.slice(0,n).map((tpl,i)=>({name:t(tpl.key),key:tpl.key,color:tpl.color,icon:tpl.icon,score:0,correct:0,wrong:0,miss:0,index:i}));currentTeam=0;}
  function renderTeams(){if(!teams.length) setupTeams();els.teams.innerHTML='';els.teams.style.gridTemplateColumns=`repeat(${Math.min(teams.length,4)},1fr)`;teams.forEach((team,i)=>{team.name=t(team.key);const pct=+els.targetScore.value?Math.min(100,Math.max(0,team.score/+els.targetScore.value*100)):Math.min(100,Math.max(0,team.score*10));const card=document.createElement('div');card.className='teamCard'+(i===currentTeam?' active':'');card.style.borderColor=i===currentTeam?team.color:'transparent';card.innerHTML=`<div class="teamName"><span class="teamDot" style="background:${team.color}"></span>${team.icon} ${team.name}</div><div class="teamScore">${team.score}</div><div class="teamMeta">✅ ${team.correct}　❌ ${team.wrong}　⏱ ${team.miss}</div><div class="bar"><div class="barFill" style="width:${pct}%"></div></div>`;els.teams.appendChild(card);});if(teams[currentTeam]) els.turnName.textContent=teams[currentTeam].name;}
  function createHoles(){els.holes.innerHTML='';for(let i=0;i<9;i++){const hole=document.createElement('div');hole.className='hole';const btn=document.createElement('button');btn.className='mole';btn.type='button';btn.dataset.hole=i;btn.addEventListener('click',()=>hitMole(btn));hole.appendChild(btn);els.holes.appendChild(hole);}}
  function saveSettings(){const keys=['lang','teamCount','gameTime','roundTime','targetScore','correctPoint','wrongPenalty','moleSpeed','answerCount','questionMode','sound','afterCorrect','afterWrong','questionBank'];const data={};keys.forEach(k=>{data[k]=els[k]?.value});localStorage.setItem('whackMoleQuizSettings',JSON.stringify(data));}
  function loadSettings(){try{const data=JSON.parse(localStorage.getItem('whackMoleQuizSettings')||'{}');Object.keys(data).forEach(k=>{if(els[k]) els[k].value=data[k];});}catch(e){}if(!els.questionBank.value.trim()) els.questionBank.value=sampleBank;}
  function beep(type){if(els.sound.value!=='on') return;try{const ctx=new (window.AudioContext||window.webkitAudioContext)();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type='sine';osc.frequency.value=type==='good'?880:type==='bad'?180:type==='warn'?420:520;gain.gain.setValueAtTime(.001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+(type==='bad'?.32:.18));osc.start();osc.stop(ctx.currentTime+(type==='bad'?.34:.2));}catch(e){}}
  function addLog(text){logs.unshift(text);logs=logs.slice(0,20);els.logList.innerHTML=logs.map(x=>`<div class="logItem">${x}</div>`).join('');}
  function startGame(){saveSettings();questions=parseBank();if(!questions.length){alert(t('emptyBank'));return;}if(questions.some(q=>!q.q||!q.correct)){alert(t('badBank'));return;}setupTeams();roundNo=0;qIndex=0;logs=[];els.logList.innerHTML='';running=true;paused=false;answered=false;gameLeft=+els.gameTime.value;els.gameTimer.textContent=+els.gameTime.value?fmt(gameLeft):'∞';els.layout.classList.add('playing');$('showSettingsBtn').classList.remove('hidden');els.pauseBtn.textContent=t('pause');els.feedback.textContent=t('startMsg');renderTeams();clearTimers();if(+els.gameTime.value){gameTimerInt=setInterval(()=>{if(!running||paused)return;gameLeft--;els.gameTimer.textContent=fmt(gameLeft);if(gameLeft<=0) endGame();},1000);}nextRound();}
  function clearTimers(){clearInterval(gameTimerInt);clearInterval(roundTimerInt);clearInterval(moleInt);gameTimerInt=roundTimerInt=moleInt=null;}
  function buildOptions(q){const desired=+els.answerCount.value;let opts=[q.correct,...q.distractors].map(x=>String(x).trim()).filter(Boolean);const other=questions.map(x=>x.correct).filter(x=>norm(x)!==norm(q.correct));opts=[...new Set(opts.map(x=>String(x)))];while(opts.length<desired&&other.length){const pick=shuffle(other).find(x=>!opts.some(o=>norm(o)===norm(x)));if(!pick)break;opts.push(pick);}return shuffle(opts).slice(0,Math.min(desired,9));}
  function chooseQuestion(){if(els.questionMode.value==='order'){const q=questions[qIndex%questions.length];qIndex++;return q;}return questions[Math.floor(Math.random()*questions.length)];}
  function nextRound(){if(!running||paused)return;if(checkTarget())return;answered=false;roundNo++;currentQuestion=chooseQuestion();currentOptions=buildOptions(currentQuestion);els.questionNo.textContent='#'+roundNo;els.questionText.textContent=currentQuestion.q;els.questionHint.textContent=t('hitHint');els.feedback.innerHTML=`${t('round',{n:roundNo})} · ${teams[currentTeam].icon} <b>${teams[currentTeam].name}</b>`;roundLeft=+els.roundTime.value;els.roundTimer.textContent=roundLeft?roundLeft:'∞';els.roundFill.style.width='100%';renderTeams();startMoles();clearInterval(roundTimerInt);if(roundLeft>0){const total=roundLeft;roundTimerInt=setInterval(()=>{if(!running||paused||answered)return;roundLeft--;els.roundTimer.textContent=roundLeft;els.roundFill.style.width=Math.max(0,roundLeft/total*100)+'%';if(roundLeft<=0) handleTimeout();},1000);}}
  function startMoles(){clearInterval(moleInt);showMoles();moleInt=setInterval(()=>{if(!running||paused||answered)return;showMoles();},+els.moleSpeed.value);}
  function showMoles(){const btns=[...els.holes.querySelectorAll('.mole')];btns.forEach(b=>{b.className='mole';b.textContent='';delete b.dataset.answer;});const holes=shuffle([...Array(9).keys()]).slice(0,currentOptions.length);currentOptions.forEach((opt,i)=>{const b=btns[holes[i]];b.textContent=opt;b.dataset.answer=opt;setTimeout(()=>b.classList.add('show'),20+i*25);});}
  function hitMole(btn){if(!running||paused||answered)return;const ans=btn.dataset.answer;if(!ans)return;answered=true;clearInterval(roundTimerInt);clearInterval(moleInt);const isCorrect=norm(ans)===norm(currentQuestion.correct);btn.classList.add(isCorrect?'correctHit':'wrongHit');btn.classList.add('show');if(isCorrect) handleCorrect(ans); else handleWrong(ans);}
  function handleCorrect(ans){const team=teams[currentTeam];team.score+=+els.correctPoint.value;team.correct++;beep('good');els.feedback.innerHTML=`✅ <b>${t('correct')}</b> ${team.name} +${els.correctPoint.value}<br>${t('correctAnswer')}：<b>${currentQuestion.correct}</b>`;addLog(`✅ ${team.name}: ${currentQuestion.q} → ${currentQuestion.correct}`);renderTeams();if(checkTarget())return;setTimeout(()=>{if(els.afterCorrect.value==='switch') switchTeam();nextRound();},850);}
  function handleWrong(ans){const team=teams[currentTeam];const pen=+els.wrongPenalty.value;if(pen) team.score-=pen;team.wrong++;beep('bad');els.feedback.innerHTML=`❌ <b>${t('wrong')}</b> ${team.name}${pen?` -${pen}`:''}<br>${t('correctAnswer')}：<b>${currentQuestion.correct}</b>`;addLog(`❌ ${team.name}: ${currentQuestion.q} / ${t('correctAnswer')}: ${currentQuestion.correct}`);renderTeams();setTimeout(()=>{if(els.afterWrong.value==='switch') switchTeam();nextRound();},1150);}
  function handleTimeout(){if(!running||answered)return;answered=true;clearInterval(roundTimerInt);clearInterval(moleInt);const team=teams[currentTeam];const pen=+els.wrongPenalty.value;if(pen) team.score-=pen;team.miss++;beep('warn');els.feedback.innerHTML=`⏱ <b>${t('timeout')}</b> ${team.name}${pen?` -${pen}`:''}<br>${t('correctAnswer')}：<b>${currentQuestion.correct}</b>`;addLog(`⏱ ${team.name}: ${t('timeout')} / ${currentQuestion.correct}`);renderTeams();setTimeout(()=>{if(els.afterWrong.value==='switch') switchTeam();nextRound();},1150);}
  function switchTeam(){currentTeam=(currentTeam+1)%teams.length;renderTeams();}
  function skipQuestion(){if(!running)return;answered=true;clearInterval(roundTimerInt);clearInterval(moleInt);addLog(`⏭ ${t('skipMsg')}`);els.feedback.textContent=t('skipMsg');switchTeam();setTimeout(()=>nextRound(),500);}
  function togglePause(){if(!running)return;paused=!paused;els.pauseBtn.textContent=paused?t('resume'):t('pause');els.feedback.textContent=paused?t('paused'):t('startMsg');if(paused){clearInterval(moleInt);}else{startMoles();}}
  function checkTarget(){const target=+els.targetScore.value;if(target>0&&teams.some(x=>x.score>=target)){endGame();return true;}return false;}
  function endGame(){if(!running)return;running=false;paused=false;clearTimers();els.layout.classList.remove('playing');const sorted=[...teams].sort((a,b)=>b.score-a.score||b.correct-a.correct);let html=`<h2 style="margin-top:0">🏆 ${t('ranking')}</h2>`;html+=sorted.map((team,i)=>`<div class="rankRow"><div class="rankMedal">${i===0?'🥇':i===1?'🥈':i===2?'🥉':'🎖️'}</div><div><div style="font-size:20px">${team.icon} ${team.name}</div><div style="color:#64748b;font-size:13px">✅ ${team.correct}　❌ ${team.wrong}　⏱ ${team.miss}</div></div><div class="rankScore">${team.score} ${t('score')}</div></div>`).join('');els.modalBody.innerHTML=html;els.modalBackdrop.classList.add('show');beep('good');renderTeams();}
  function resetGame(){running=false;paused=false;clearTimers();setupTeams();roundNo=0;logs=[];els.logList.innerHTML='';els.layout.classList.remove('playing');els.gameTimer.textContent=+els.gameTime.value?fmt(+els.gameTime.value):'∞';els.roundTimer.textContent=+els.roundTime.value||'∞';els.roundFill.style.width='100%';els.questionNo.textContent='#0';els.questionText.textContent=t('readyText');els.questionHint.textContent=t('readyHint');els.feedback.textContent=t('feedbackReady');renderTeams();createHoles();}
  function exportTxt(){const blob=new Blob([els.questionBank.value],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='whack_a_mole_question_bank.txt';a.click();URL.revokeObjectURL(a.href);}
  function importTxt(file){const reader=new FileReader();reader.onload=()=>{els.questionBank.value=reader.result;saveSettings();};reader.readAsText(file,'utf-8');}
  function fullscreen(){const el=document.documentElement;if(!document.fullscreenElement) el.requestFullscreen?.(); else document.exitFullscreen?.();}
  function bind(){document.querySelectorAll('select,textarea').forEach(el=>el.addEventListener('change',()=>{saveSettings();if(el===els.lang) applyI18n(); else {updateDynamicTexts();renderTeams();}}));els.lang.addEventListener('change',applyI18n);$('startBtn').addEventListener('click',startGame);$('resetBtn').addEventListener('click',resetGame);$('fullscreenBtn').addEventListener('click',fullscreen);$('showSettingsBtn').addEventListener('click',()=>els.layout.classList.toggle('playing'));$('nextBtn').addEventListener('click',skipQuestion);els.pauseBtn.addEventListener('click',togglePause);$('exportBtn').addEventListener('click',exportTxt);$('importBtn').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',e=>{if(e.target.files[0]) importTxt(e.target.files[0]);e.target.value='';});$('closeModal').addEventListener('click',()=>els.modalBackdrop.classList.remove('show'));els.modalBackdrop.addEventListener('click',e=>{if(e.target===els.modalBackdrop) els.modalBackdrop.classList.remove('show');});}
  loadSettings();bind();applyI18n();setupTeams();createHoles();resetGame();
})();
