const STORAGE_KEYS={levels:'fdg_levels_v2',rankings:'fdg_rankings_v2',player:'fdg_player_v2',admin:'fdg_admin_logged_v2'};
const ADMIN_USER='admin',ADMIN_PASS='123456';
const defaultLevel={id:'demo-level-1',levelNumber:1,title:'示例关卡',timeLimit:60,hintLimit:3,totalDifferences:0,isActive:true,leftImage:'',rightImage:'',answerMask:''};
const App={
  levels:[],rankings:[],currentLevelIndex:0,timer:null,timeLeft:0,score:0,hintsLeft:0,foundRegions:new Set(),currentRegions:[],currentMaskInfo:null,playerName:'游客',editingId:null,
  init(){this.bootstrapLevels();this.rankings=loadJSON(STORAGE_KEYS.rankings,[]);this.playerName=localStorage.getItem(STORAGE_KEYS.player)||'游客';$('playerText').textContent=this.playerName;$('playerNameInput').value=this.playerName==='游客'?'':this.playerName;this.bindNav();this.bindGame();this.bindAdmin();this.renderRankings();this.renderAdminTable();this.loadFirstPlayableLevel()},
  bootstrapLevels(){const saved=loadJSON(STORAGE_KEYS.levels,null);this.levels=Array.isArray(saved)&&saved.length?saved.sort((a,b)=>a.levelNumber-b.levelNumber):[structuredClone(defaultLevel)];saveJSON(STORAGE_KEYS.levels,this.levels)},
  bindNav(){$('navGame').onclick=()=>this.show('viewGame');$('navRanking').onclick=()=>{this.renderRankings();this.show('viewRanking')};$('navAdmin').onclick=()=>{this.show('viewAdmin');const logged=localStorage.getItem(STORAGE_KEYS.admin)==='1';$('adminLogin').classList.toggle('hidden',logged);$('adminPanel').classList.toggle('hidden',!logged)}},
  show(id){['viewGame','viewRanking','viewAdmin'].forEach(v=>$(v).classList.add('hidden'));$(id).classList.remove('hidden')},
  async loadFirstPlayableLevel(){const idx=this.levels.findIndex(l=>l.isActive&&l.leftImage&&l.rightImage&&l.answerMask);this.currentLevelIndex=idx>=0?idx:0;await this.renderLevel()},
  async renderLevel(){const level=this.levels[this.currentLevelIndex];if(!level)return;$('levelText').textContent=String(level.levelNumber||1);$('timerText').textContent=String(level.timeLimit||60);$('scoreText').textContent=String(this.score);this.hintsLeft=Number(level.hintLimit||0);$('hintText').textContent=String(this.hintsLeft);$('gameMsg').textContent='';$('gameMsg').className='msg';this.foundRegions=new Set();this.currentRegions=[];this.currentMaskInfo=null;$('foundText').textContent=`0/${level.totalDifferences||0}`;this.clearAllOverlayCanvas();await this.drawBaseCanvas('leftCanvas','leftOverlay',level.leftImage);await this.drawBaseCanvas('rightCanvas','rightOverlay',level.rightImage);if(level.answerMask){try{const maskInfo=await extractMaskRegions(level.answerMask);this.currentMaskInfo=maskInfo;this.currentRegions=maskInfo.regions;if(!level.totalDifferences||level.totalDifferences!==maskInfo.regions.length){level.totalDifferences=maskInfo.regions.length;this.persistLevels()}$('foundText').textContent=`0/${level.totalDifferences}`}catch(e){console.error(e);this.flashMsg('答案图读取失败','bad')}}},
  async drawBaseCanvas(baseId,overlayId,src){const base=$(baseId),overlay=$(overlayId),ctx=base.getContext('2d');ctx.clearRect(0,0,base.width,base.height);if(!src){base.width=600;base.height=420;overlay.width=600;overlay.height=420;ctx.fillStyle='#e5e7eb';ctx.fillRect(0,0,base.width,base.height);ctx.fillStyle='#6b7280';ctx.font='20px sans-serif';ctx.fillText('请先在后台上传关卡图片',30,60);return}const img=await dataUrlToImage(src);base.width=img.width;base.height=img.height;overlay.width=img.width;overlay.height=img.height;ctx.drawImage(img,0,0)},
  bindGame(){$('btnStart').onclick=()=>this.startLevel();$('btnRestart').onclick=()=>this.restartLevel();$('btnNext').onclick=()=>this.nextLevel();$('btnHint').onclick=()=>this.useHint();$('btnFullscreen').onclick=()=>this.toggleFullscreen();$('savePlayerName').onclick=()=>{const name=$('playerNameInput').value.trim();if(!name)return;this.playerName=name;localStorage.setItem(STORAGE_KEYS.player,name);$('playerText').textContent=name;this.flashMsg('玩家名字已保存','ok')};$('clearRanking').onclick=()=>{if(!confirm('确定清空排行榜吗？'))return;this.rankings=[];saveJSON(STORAGE_KEYS.rankings,this.rankings);this.renderRankings()};['leftCanvas','rightCanvas'].forEach(baseId=>$(baseId).addEventListener('click',e=>this.handleCanvasClick(baseId,e)));window.addEventListener('resize',()=>this.redrawPersistentMarks())},
  handleCanvasClick(baseId,e){const level=this.levels[this.currentLevelIndex];if(!level||!level.answerMask||!this.timer)return;const canvas=$(baseId),rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;const hitInfo=getMaskHitInfo(this.currentMaskInfo,x,y,rect.width,rect.height);if(!hitInfo.hit){this.score=Math.max(0,this.score-5);$('scoreText').textContent=String(this.score);this.drawMissMark(baseId==='leftCanvas'?'leftOverlay':'rightOverlay',x,y,rect.width,rect.height);this.flashMsg('点错了，显示 X，扣 5 分','bad');playBeep('bad');return}const region=this.currentRegions.find(r=>r.id===hitInfo.regionId);if(!region){this.flashMsg('命中红区但找不到对应区域','warn');return}if(this.foundRegions.has(region.id)){this.flashMsg('这个差异已经找过了','warn');return}this.foundRegions.add(region.id);this.score+=10;$('scoreText').textContent=String(this.score);$('foundText').textContent=`${this.foundRegions.size}/${level.totalDifferences}`;this.redrawPersistentMarks();this.flashMsg('找到了，立即出圈，+10 分','ok');playBeep('ok');if(this.foundRegions.size>=level.totalDifferences){clearInterval(this.timer);this.timer=null;this.score+=20;$('scoreText').textContent=String(this.score);this.flashMsg('过关成功，奖励 +20 分','ok');playBeep('win');this.saveRanking(level.levelNumber)}},
  startLevel(){this.toggleFullscreen(true);const level=this.levels[this.currentLevelIndex];if(!level||!level.leftImage||!level.rightImage||!level.answerMask){this.flashMsg('当前关卡尚未完整上传左图、右图、答案图','bad');return}if(this.timer)clearInterval(this.timer);this.timeLeft=Number(level.timeLimit||60);$('timerText').textContent=String(this.timeLeft);this.flashMsg('游戏开始，请找出所有差异','ok');this.timer=setInterval(()=>{this.timeLeft-=1;$('timerText').textContent=String(this.timeLeft);if(this.timeLeft<=0){clearInterval(this.timer);this.timer=null;this.flashMsg('时间到，挑战失败','bad');playBeep('lose')}},1000)},
  async restartLevel(){if(this.timer){clearInterval(this.timer);this.timer=null}await this.renderLevel();this.startLevel()},
  async nextLevel(){const active=this.levels.filter(l=>l.isActive&&l.leftImage&&l.rightImage&&l.answerMask).sort((a,b)=>a.levelNumber-b.levelNumber);if(!active.length){this.flashMsg('没有可玩的关卡，请先到后台上传','bad');return}const currentId=this.levels[this.currentLevelIndex]?.id,pos=active.findIndex(l=>l.id===currentId),next=active[(pos+1)%active.length];this.currentLevelIndex=this.levels.findIndex(l=>l.id===next.id);await this.renderLevel();this.startLevel()},
  useHint(){if(!this.timer){this.flashMsg('请先开始游戏','warn');return}if(this.hintsLeft<=0){this.flashMsg('提示次数已用完','bad');return}const remain=this.currentRegions.filter(r=>!this.foundRegions.has(r.id));if(!remain.length){this.flashMsg('没有可提示的差异了','warn');return}const region=remain[0];this.hintsLeft-=1;this.score=Math.max(0,this.score-3);$('hintText').textContent=String(this.hintsLeft);$('scoreText').textContent=String(this.score);this.drawHintRegion(region);this.flashMsg('已提示一个位置，扣 3 分','warn');playBeep('hint')},
  toggleFullscreen(forceEnter=false){const el=document.documentElement;try{if(forceEnter){if(!document.fullscreenElement&&el.requestFullscreen)el.requestFullscreen();return}if(!document.fullscreenElement){if(el.requestFullscreen)el.requestFullscreen()}else if(document.exitFullscreen)document.exitFullscreen()}catch{}},
  clearAllOverlayCanvas(){['leftOverlay','rightOverlay'].forEach(id=>{const o=$(id);if(!o)return;o.getContext('2d').clearRect(0,0,o.width,o.height)})},
  drawRegionRectOnOverlay(overlayId,region,strokeStyle,dashed=false){const overlay=$(overlayId);if(!overlay||!region)return;const ctx=overlay.getContext('2d');ctx.save();ctx.strokeStyle=strokeStyle;ctx.lineWidth=6;ctx.setLineDash(dashed?[14,10]:[]);const pad=12,x=Math.max(0,region.minX-pad),y=Math.max(0,region.minY-pad),w=Math.min(overlay.width-x,(region.maxX-region.minX+1)+pad*2),h=Math.min(overlay.height-y,(region.maxY-region.minY+1)+pad*2);ctx.strokeRect(x,y,w,h);ctx.restore()},
  redrawPersistentMarks(){this.clearAllOverlayCanvas();this.foundRegions.forEach(regionId=>{const region=this.currentRegions.find(r=>r.id===regionId);if(!region)return;this.drawRegionRectOnOverlay('leftOverlay',region,'#16a34a',false);this.drawRegionRectOnOverlay('rightOverlay',region,'#16a34a',false)})},
  drawHintRegion(region){this.redrawPersistentMarks();this.drawRegionRectOnOverlay('leftOverlay',region,'#f59e0b',true);this.drawRegionRectOnOverlay('rightOverlay',region,'#f59e0b',true);setTimeout(()=>this.redrawPersistentMarks(),2000)},
  drawMissMark(overlayId,displayX,displayY,displayWidth,displayHeight){const overlay=$(overlayId);if(!overlay)return;const ctx=overlay.getContext('2d'),x=displayX*(overlay.width/displayWidth),y=displayY*(overlay.height/displayHeight);ctx.save();ctx.strokeStyle='#dc2626';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x-16,y-16);ctx.lineTo(x+16,y+16);ctx.moveTo(x+16,y-16);ctx.lineTo(x-16,y+16);ctx.stroke();ctx.restore();setTimeout(()=>this.redrawPersistentMarks(),900)},
  flashMsg(text,type='ok'){const el=$('gameMsg');el.textContent=text;el.className=`msg ${type==='ok'?'ok':type==='bad'?'bad':'warn'}`},
  saveRanking(levelNumber){const level=this.levels[this.currentLevelIndex],timeUsed=Number(level.timeLimit||60)-this.timeLeft;this.rankings.push({name:this.playerName||'游客',score:this.score,level:levelNumber,timeUsed,at:new Date().toISOString()});this.rankings.sort((a,b)=>b.score-a.score||a.timeUsed-b.timeUsed);this.rankings=this.rankings.slice(0,10);saveJSON(STORAGE_KEYS.rankings,this.rankings);this.renderRankings()},
  renderRankings(){const box=$('rankingList');box.innerHTML='';if(!this.rankings.length){box.innerHTML='<div class="card">目前还没有排行榜记录</div>';return}this.rankings.forEach((r,i)=>{const div=document.createElement('div');div.className='rank-item';div.innerHTML=`<div class="badge">${i+1}</div><div><div style="font-weight:700">${escapeHtml(r.name)}</div><div style="color:var(--muted);font-size:13px;margin-top:4px;">通关关卡：第 ${r.level} 关｜耗时：${r.timeUsed} 秒</div></div><div style="font-size:22px;font-weight:800;color:var(--primary)">${r.score}</div>`;box.appendChild(div)})},
  bindAdmin(){$('adminLoginBtn').onclick=()=>{const ok=$('adminUser').value===ADMIN_USER&&$('adminPass').value===ADMIN_PASS;$('adminLoginMsg').textContent=ok?'登录成功':'账号或密码错误';$('adminLoginMsg').className=`msg ${ok?'ok':'bad'}`;if(ok){localStorage.setItem(STORAGE_KEYS.admin,'1');$('adminLogin').classList.add('hidden');$('adminPanel').classList.remove('hidden');this.renderAdminTable()}};$('adminLogoutBtn').onclick=()=>{localStorage.removeItem(STORAGE_KEYS.admin);$('adminLogin').classList.remove('hidden');$('adminPanel').classList.add('hidden')};$('newLevelBtn').onclick=()=>this.resetForm();$('resetFormBtn').onclick=()=>this.resetForm();$('fMask').addEventListener('change',async()=>this.updateMaskPreviewFromFiles());$('fRight').addEventListener('change',async()=>this.updateMaskPreviewFromFiles());$('saveLevelBtn').onclick=async()=>this.saveLevelFromForm()},
  async updateMaskPreviewFromFiles(){const maskFile=$('fMask').files?.[0],rightFile=$('fRight').files?.[0];const maskData=maskFile?await fileToDataURL(maskFile):'';const rightData=rightFile?await fileToDataURL(rightFile):'';this.setMaskPreview(maskData,rightData)},
  async saveLevelFromForm(){try{const levelNumber=Number($('fLevelNumber').value||0),title=$('fTitle').value.trim(),timeLimit=Number($('fTimeLimit').value||60),hintLimit=Number($('fHintLimit').value||3),isActive=$('fActive').value==='true';let totalDifferences=Number($('fTotal').value||0);if(!levelNumber||!title)throw new Error('请填写关卡编号与关卡名称');const leftFile=$('fLeft').files?.[0],rightFile=$('fRight').files?.[0],maskFile=$('fMask').files?.[0];let item=this.editingId?this.levels.find(l=>l.id===this.editingId):null;if(!item){item={id:crypto.randomUUID()};this.levels.push(item)}Object.assign(item,{levelNumber,title,timeLimit,hintLimit,isActive,totalDifferences});if(leftFile)item.leftImage=await fileToDataURL(leftFile);if(rightFile)item.rightImage=await fileToDataURL(rightFile);if(maskFile)item.answerMask=await fileToDataURL(maskFile);if(!item.leftImage||!item.rightImage||!item.answerMask)throw new Error('左图、右图、答案图都必须存在');const maskInfo=await extractMaskRegions(item.answerMask);if(!totalDifferences)item.totalDifferences=maskInfo.regions.length;this.persistLevels();this.renderAdminTable();this.resetForm();$('adminMsg').textContent='关卡保存成功';$('adminMsg').className='msg ok';await this.loadFirstPlayableLevel()}catch(e){$('adminMsg').textContent=e.message||'保存失败';$('adminMsg').className='msg bad'}},
  persistLevels(){this.levels.sort((a,b)=>a.levelNumber-b.levelNumber);saveJSON(STORAGE_KEYS.levels,this.levels)},
  renderAdminTable(){const tbody=$('levelTable');tbody.innerHTML='';this.levels.sort((a,b)=>a.levelNumber-b.levelNumber).forEach(level=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${level.levelNumber}</td><td><div style="font-weight:700">${escapeHtml(level.title||'')}</div><div style="color:var(--muted);font-size:12px;">差异：${level.totalDifferences||0}｜时间：${level.timeLimit||60}s</div></td><td>${level.leftImage?`<img class="thumb" src="${level.leftImage}" alt="thumb">`:'-'}</td><td>${level.isActive?'启用':'停用'}</td><td><div style="display:flex;gap:8px;flex-wrap:wrap;"><button type="button" class="btn" data-action="edit" data-id="${level.id}">编辑</button><button type="button" class="btn danger" data-action="delete" data-id="${level.id}">删除</button></div></td>`;tbody.appendChild(tr)});if(!tbody.dataset.bound){tbody.addEventListener('click',e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;if(btn.dataset.action==='edit')this.fillForm(btn.dataset.id);if(btn.dataset.action==='delete')this.deleteLevel(btn.dataset.id)});tbody.dataset.bound='1'}},
  fillForm(id){const item=this.levels.find(l=>l.id===id);if(!item)return;this.editingId=id;$('fLevelNumber').value=item.levelNumber||'';$('fTitle').value=item.title||'';$('fTimeLimit').value=item.timeLimit||60;$('fHintLimit').value=item.hintLimit||3;$('fActive').value=String(item.isActive);$('fTotal').value=item.totalDifferences||'';$('adminMsg').textContent='已载入关卡资料，如需更换图片请重新选择文件';$('adminMsg').className='msg warn';this.setMaskPreview(item.answerMask||'',item.rightImage||'')},
  deleteLevel(id){if(!id)return;if(!confirm('确定删除这个关卡吗？'))return;const deletingCurrent=this.levels[this.currentLevelIndex]?.id===id;this.levels=this.levels.filter(l=>l.id!==id);if(this.editingId===id)this.editingId=null;if(!this.levels.length)this.levels=[{...structuredClone(defaultLevel),id:crypto.randomUUID()}];this.persistLevels();this.renderAdminTable();this.resetForm();$('adminMsg').textContent='关卡已删除';$('adminMsg').className='msg ok';if(deletingCurrent||this.currentLevelIndex>=this.levels.length){this.currentLevelIndex=0;this.loadFirstPlayableLevel()}},
  resetForm(){this.editingId=null;$('fLevelNumber').value='';$('fTitle').value='';$('fTimeLimit').value=60;$('fHintLimit').value=3;$('fActive').value='true';$('fTotal').value='';$('fLeft').value='';$('fRight').value='';$('fMask').value='';this.setMaskPreview('','')},
  setMaskPreview(maskSrc,rightSrc=''){const empty=$('maskPreviewEmpty'),stack=$('maskPreviewStack'),rightImg=$('maskPreviewRight'),maskImg=$('maskPreviewImg');if(!maskSrc){stack.classList.add('hidden');empty.classList.remove('hidden');rightImg.src='';maskImg.src='';return}rightImg.src=rightSrc||'';maskImg.src=maskSrc;stack.classList.remove('hidden');empty.classList.add('hidden')}
};
App.init();
